### ISSUE TITLE
Instant segfault on Gentoo

### ISSUE THREAD

**Issue by ajakk** [dpayne/cli-visualizer#102]
Using the current version from this repo's master branch. I'm building manually (outside of portage) and everything goes fine until I run `vis`, at that time the program quits with a segmentation fault.

I've tested it against ncurses-6.1-r2 and ncurses-5.9-r101. fftw is version 3.3.6_p2.

**Comment by SHGuy1** [comment]
#94 same

**Comment by HenkPoley** [comment]
Fix over here: 
https://github.com/dpayne/cli-visualizer/issues/94#issuecomment-426929037

More Gentoo background for the fix: 
https://github.com/dpayne/cli-visualizer/issues/108

**Comment by dpayne** [comment]
Closing this as a duplicate. It _should_ be fixed in master.
