### ISSUE TITLE
Maroon Bars when Overriding Terminal Colours

### ISSUE THREAD

**Issue by stellarpower** [dpayne/cli-visualizer#103]
Hi,

Firstly, love this to bits! I'm hoping to spend some time to add more visualisations soon.

So far I've been playing and have turned on overriding the terminal's colours, as I'm sshing into my laptop on really old Android phones as a cheaper alternative than investing in LED lights for parties, and the ssh terminal emulators for Android have some colour schemes that don't quite work. I have tried using an x server but this is slow so ssh seems the way. Anyway, overriding the colour scheme is perfect except that there seems to be a rogue burgundy/maroon colour inbetween the greens in Rainbow that isn't there when the terminal colours are used.

Github's failing to upload the image [so here it is externally](https://imagebin.ca/v/4DhmND819mJb)

I'm also a bit suspicious as this looks very close to the Ubuntu 'Aubergine' even though its hex value doesn't match any official Canonical colour value.

I was wondering if this is a bug where you think would be good to start looking for it.

Thanks!

**Comment by dpayne** [comment]
Do you have your full color config? Last time I noticed this it was because I didn't have a particular color mapped.

**Comment by stellarpower** [comment]
Afaik I was just using the rainbow out of the box but will reinstall when
I'm next at my machine and check I've not fudged it.

Thanks

**Comment by stellarpower** [comment]
Yeah reinstalling that file has fixed it, not sure what happened as I checked the individual colours too. Thanks!
