### ISSUE TITLE
Colors are not restored on terminal when program is closed

### ISSUE THREAD

**Issue by maxice8** [dpayne/cli-visualizer#106]
Before (colorscheme as normal):
![image](https://user-images.githubusercontent.com/30738253/45201563-5d74e280-b24c-11e8-905f-b3385dce4775.png)

During (works as intended):
![image](https://user-images.githubusercontent.com/30738253/45201573-6e255880-b24c-11e8-9b3d-04d0029fadc5.png)

After (colorscheme not restored):
![image](https://user-images.githubusercontent.com/30738253/45201593-81382880-b24c-11e8-93f1-2d7d757f188a.png)

**Comment by Gigahawk** [comment]
The readme mentions that you can disable overriding the terminal colors by setting
```
colors.override.terminal=false
```

**Comment by maxice8** [comment]
oh i see
