### ISSUE TITLE
ld libtinfo error with Makefile

### ISSUE THREAD

**Issue by Pixadus** [dpayne/cli-visualizer#110]
When compiling under the default instructions on Debian 9.5 Stretch, I ran into an error `/usr/bin/ld: cannot find -ltinfow` near the end of the execution sequence... after a bit of research, I changed all references to `ltinfow` in the Makefile to `ltinfo` and it compiled vis successfully. 

Is anyone else getting this?

**Comment by dpayne** [comment]
This should be fixed with the new cmake build process. Same method to build and install `./install.sh`, but cmake is now a required.
