### ISSUE TITLE
It appears a file is missing 

### ISSUE THREAD

**Issue by CryCic4da** [dpayne/cli-visualizer#113]
fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vis.dir/build.make:279: CMakeFiles/vis.dir/src/Transformer/SpectrumCircleTransformer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/vis.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

https://packages.gentoo.org/packages/sci-libs/fftw
I suppose this is the one that is missing for Gentoo. Could you add this one to the read.me?

**Comment by CryCic4da** [comment]
It appears that this file should be in a standard library. Which one?

**Comment by CryCic4da** [comment]
https://packages.gentoo.org/packages/sci-libs/fftw
I suppose this is the one that is missing for Gentoo. Could you add this one to the read.me?

**Comment by CryCic4da** [comment]
I am blind. It is in there, just not under the gentoo section.

**Comment by dpayne** [comment]
@CryCic4da you are not blind I just updated the docs : )
