### ISSUE TITLE
Cannot Install Because Of mvaddwstr From ncursesw

### ISSUE THREAD

**Issue by CryCic4da** [dpayne/cli-visualizer#114]
Stuck with a different error. Tried to search online a bit but no success as of yet. It shows that height and width are declared nearly everywhere but never used and then at 94% it says mvaddwstr is never declared. NcurseUtils.h also seems to have an issue that doesn't make sense because in the code the variables are indeed used. Could you please have a look? I really enjoy your vis.

running $ locate ncurses.h
returns
/usr/include/ncurses.h
/usr/include/ncursesw/ncurses.h

[ 89%] Building CXX object CMakeFiles/vis.dir/src/Visualizer.cpp.o
In file included from /home/user/Documents/Github Files/cli-visualizer/src/Visualizer.cpp:18:0:
/home/user/Documents/Github Files/cli-visualizer/src/Utils/NcursesUtils.h: In static member function ‘static int32_t vis::NcursesUtils::get_window_width()’:
/home/user/Documents/Github Files/cli-visualizer/src/Utils/NcursesUtils.h:109:24: warning: variable ‘height’ set but not used [-Wunused-but-set-variable]
         int32_t width, height;
                        ^~~~~~

[ 94%] Building CXX object CMakeFiles/vis.dir/src/Writer/NcursesWriter.cpp.o
In file included from /home/user/Documents/Github Files/cli-visualizer/src/Writer/NcursesWriter.cpp:11:0:
/home/user/Documents/Github Files/cli-visualizer/src/Utils/NcursesUtils.h: In static member function ‘static int32_t vis::NcursesUtils::get_window_width()’:
/home/user/Documents/Github Files/cli-visualizer/src/Utils/NcursesUtils.h:109:24: warning: variable ‘height’ set but not used [-Wunused-but-set-variable]
         int32_t width, height;
                        ^~~~~~

/home/user/Documents/Github Files/cli-visualizer/src/Writer/NcursesWriter.cpp: In member function ‘void vis::NcursesWriter::write_background(int32_t, int32_t, vis::ColorDefinition, const wstring&)’:
/home/user/Documents/Github Files/cli-visualizer/src/Writer/NcursesWriter.cpp:90:5: error: ‘mvaddwstr’ was not declared in this scope
     mvaddwstr(height, width, msg.c_str());
     ^~~~~~~~~

/home/user/Documents/Github Files/cli-visualizer/src/Writer/NcursesWriter.cpp:90:5: note: suggested alternative: ‘mvaddstr’
     mvaddwstr(height, width, msg.c_str());
     ^~~~~~~~~
     mvaddstr

/home/user/Documents/Github Files/cli-visualizer/src/Writer/NcursesWriter.cpp: In member function ‘void vis::NcursesWriter::write_foreground(int32_t, int32_t, vis::ColorDefinition, const wstring&)’:

/home/user/Documents/Github Files/cli-visualizer/src/Writer/NcursesWriter.cpp:102:5: error: ‘mvaddwstr’ was not declared in this scope
     mvaddwstr(height, width, msg.c_str());
     ^~~~~~~~~

/home/user/Documents/Github Files/cli-visualizer/src/Writer/NcursesWriter.cpp:102:5: note: suggested alternative: ‘mvaddstr’
     mvaddwstr(height, width, msg.c_str());
     ^~~~~~~~~
     mvaddstr

make[2]: *** [CMakeFiles/vis.dir/build.make:471: CMakeFiles/vis.dir/src/Writer/NcursesWriter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/vis.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by CryCic4da** [comment]
So what I did is I edited the NcursesWriter.h file to just include 
`//#ifdef NCURSESW
#include <ncursesw/ncurses.h>
//#else
//#include <ncurses.h>
//#endif
`
So now it managed to compile. Will double check everything now to see if it still does what it needs to do. Why did you write the ifdef? Is there a reason one would not have the ncurses.h from ncursesw? More over why would this be my culprit?

**Comment by dpayne** [comment]
Some systems put ncursesw in the regular ncurses header so I can't always use ```<ncursesw/ncurses.h>```. My hunch is this is caused by the recent switch to cmake, if I have some time this weekend I'll dive into it more.

**Comment by dpayne** [comment]
I updated the gentoo readme section. You might to re-install ncurses

```sudo emerge fftw cmake
sudo USE="unicode" emerge ncurses```

If it's still broken let me know and I'll re-open. This is my first time use gentoo so it's very possible I screwed something up, but it appear to compile and run for me.

**Comment by rdrpenguin04** [comment]
I'm on Ubuntu, and I have this issue too. Gentoo doesn't have the same ability to rebuild packages with different settings. It would be nice to see a fix for this. Meanwhile, I'll add the header to the files on my end.
