### ISSUE TITLE
Lagging issues

### ISSUE THREAD

**Issue by gipert** [dpayne/cli-visualizer#124]
Hello there. I've been experiencing some lagging issues lately and I don't really now how to tackle them down.

My guess is that all happened after one of my last system updates. I tried to recompile the project by myself but nothing changed, I evenually also tried to set `visualizer.fps` to higher values but didn't help. I also tried to use a different terminal emulator (I'm currently on Alacritty) and I don't experience lagging in other tools that use ncurses.

I wonder if you have an idea of where the problem could be or how to debug it.

I'm running on a CentOS7, here are my [dotfiles](https://github.com/gipert/.dotfiles), if it can help.

Thanks in advance for helping :)

**Comment by dpayne** [comment]
Is it possible it's pulse or mpd causing the lag? Every system is a little different, my own lag issues were generally caused by either mpd buffering or pulse audio.

**Comment by gipert** [comment]
Oh sorry, I forgot to mention I use mpd. I'm really not an expert, what do you suggest to look for in mpd settings?

**Comment by dpayne** [comment]
Reducing the buffer is probably the best bet.

**Comment by gipert** [comment]
The issue somewhat vanished after a system reboot (yes, the first since many months ago). Sorry for spamming!
