### ISSUE TITLE
Install fails on OSX

### ISSUE THREAD

**Issue by eramdam** [dpayne/cli-visualizer#13]
When I run `./install.sh` on OSX (after installing the deps) I get this error

```bash
mkdir -p /Users/Damien/Desktop/Stuff/cli-visualizer/build
rm -f /Users/Damien/Desktop/Stuff/cli-visualizer/build/vis
c++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -dynamic -D_OS_OSX -D_XOPEN_SOURCE_EXTENDED -D_ENABLE_PULSE  -fno-omit-frame-pointer -D_XOPEN_SOURCE_EXTENDED -D_ENABLE_PULSE -I/usr/local/include -I/Users/Damien/Desktop/Stuff/cli-visualizer/include -I/Users/Damien/Desktop/Stuff/cli-visualizer/src -c src/Source/MpdAudioSource.cpp -o /Users/Damien/Desktop/Stuff/cli-visualizer/build/MpdAudioSource.o
src/Source/MpdAudioSource.cpp:80:36: error: no member named 'read' in the global namespace
            int64_t bytes_read = ::read(m_mpd_fifo_fd, buffer, bytes_left);
                                 ~~^
src/Source/MpdAudioSource.cpp:109:27: error: no type named 'close' in the global namespace
                        ::close(m_mpd_fifo_fd);
                        ~~^
src/Source/MpdAudioSource.cpp:141:11: error: no type named 'close' in the global namespace
        ::close(m_mpd_fifo_fd);
        ~~^
3 errors generated.
make: *** [/Users/Damien/Desktop/Stuff/cli-visualizer/build/MpdAudioSource.o] Error 1
```

What am I missing?

**Comment by dpayne** [comment]
One thing that I notice is that the compiler is defaulting to `c++` instead of `clang++`. Could you try running

    export VIS_COMPILER='clang++'
    make

If that still fails could you install command line tools for mac os x here https://developer.apple.com/downloads/ then try again.

**Comment by eramdam** [comment]
@dpayne I already have command line tools installed (through Xcode), I tried what you said and now the error is different 


```
damien@Oreo:~/D/cli-visualizer
<master✓> » export VIS_COMPILER='clang++'
damien@Oreo:~/D/cli-visualizer
<master✓> » make
mkdir -p /Users/damien/Desktop/cli-visualizer/build
rm -f /Users/damien/Desktop/cli-visualizer/build/vis
clang++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -Werror -Weverything -Wno-variadic-macros -Wno-format-nonliteral -Wno-global-constructors -Wno-exit-time-destructors -Wno-padded -Wno-reserved-id-macro -Wno-gnu-zero-variadic-macro-arguments -Wno-c++98-compat -dynamic -D_OS_OSX -D_XOPEN_SOURCE_EXTENDED  -fno-omit-frame-pointer -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -I/Users/damien/Desktop/cli-visualizer/include -I/Users/damien/Desktop/cli-visualizer/src -c src/Visualizer.cpp -o /Users/damien/Desktop/cli-visualizer/build/Visualizer.o
In file included from src/Visualizer.cpp:14:
/Users/damien/Desktop/cli-visualizer/src/Transformer/SpectrumTransformer.h:194:27: error: unknown command tag name
      [-Werror,-Wdocumentation-unknown-command]
     * taken from cava git@github.com:karlstav/cava.git
                          ^
1 error generated.
make: *** [/Users/damien/Desktop/cli-visualizer/build/Visualizer.o] Error 1
```

**Comment by dpayne** [comment]
Can you paste the result of what you get when you run

    clang++ --version

Also which version of mac os x are you on?

**Comment by DuckThom** [comment]
Building the app was working fine for me until I tried to build it using clang++ on Arch Linux.
Using clang++ I get the same error as @eramdam 
```
/home/luna/builds/cli-visualizer/src/Transformer/SpectrumTransformer.h:194:27: error: 
unknown command tag name [-Werror,-Wdocumentation-unknown-command]
```

However, the first time I built `vis`, I was using g++ instead of clang++. 
After changing `VIS_COMPILER` back to g++, I was able to build `vis` again.
I suspect that clang++ is the issue here, my clang++ version is: 
```
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
It looks like clang is trying to parse `git@github.com:karlstav/cava.git` as a documentation thing (like `@return`)

**Comment by DuckThom** [comment]
If i change `git@github.com:karlstav/cava.git` to `https://github.com/karlstav/cava.git` I'm able to build vis using clang++.

The following files would need to be changed: 
```
src/Transformer/SpectrumTransformer.h:194
src/Transformer/SpectrumTransformer.cpp:8
```

**Comment by dpayne** [comment]
I think you are right that has something to do with clang. What is odd is that appears to be building with and old version of C++ standard. The old standard disallowed mixing `//` comments and `/*` comments, which is why I think it is failing to build. Another odd point is that clang on arch linux and mac os x both work for me. I actually use clang by default even when building on arch.

Clang version on arch is

    ❯❯❯ clang++ --version
    clang version 3.7.1 (tags/RELEASE_371/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix

Clang version on mac os x is

    clang++ --version
    Apple LLVM version 7.0.2 (clang-700.1.81)
    Target: x86_64-apple-darwin15.2.0
    Thread model: posix


@DuckThom when building on arch linux with clang, could you paste the entire build output? It's possible one of the compile flags is not being set correctly.

**Comment by DuckThom** [comment]
Here you go:
```
[master] cli-visualizer/ $ export VIS_COMPILER="clang++"
[master] cli-visualizer/ $ make 
mkdir -p /home/luna/builds/cli-visualizer/build
rm -f /home/luna/builds/cli-visualizer/build/vis
clang++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -Werror -Weverything -Wno-variadic-macros -Wno-format-nonliteral -Wno-global-constructors -Wno-exit-time-destructors -Wno-padded -Wno-reserved-id-macro -Wno-gnu-zero-variadic-macro-arguments -Wno-c++98-compat -D_LINUX -D_ENABLE_PULSE  -fno-omit-frame-pointer -D_ENABLE_PULSE -I/usr/local/include -I/home/luna/builds/cli-visualizer/include -I/home/luna/builds/cli-visualizer/src -c src/Transformer/SpectrumTransformer.cpp -o /home/luna/builds/cli-visualizer/build/SpectrumTransformer.o
In file included from src/Transformer/SpectrumTransformer.cpp:15:
/home/luna/builds/cli-visualizer/src/Transformer/SpectrumTransformer.h:194:27: error: unknown command tag name
      [-Werror,-Wdocumentation-unknown-command]
     * taken from cava git@github.com:karlstav/cava.git
                          ^
1 error generated.
Makefile:214: recipe for target '/home/luna/builds/cli-visualizer/build/SpectrumTransformer.o' failed
make: *** [/home/luna/builds/cli-visualizer/build/SpectrumTransformer.o] Error 1
```
Removing the `@` symbol from the previously mentioned files will fix this issue for me.

**Comment by dpayne** [comment]
This should be fixed now. It was due to a new compile flag `-Wdocumentation-unknown-command` enabled under `-Weverything` on the latest version of `clang++`. It did not fail for me since I was using `ccache` to cache compilations, after clearing my cache I was able to re-produce the issue.
