### ISSUE TITLE
Unable to build on Mac

### ISSUE THREAD

**Issue by ClaytonSmith** [dpayne/cli-visualizer#14]
Following the install instructions for Mac, I get this build error.
<img width="1440" alt="screen shot 2016-04-14 at 10 15 43 am" src="https://cloud.githubusercontent.com/assets/8992035/14531119/087442dc-022a-11e6-9ec5-c8ac6cbc3f3a.png">

**Comment by dpayne** [comment]
Do you have Command Line Tools installed? https://developer.apple.com/downloads/

The build is currently working for me on

     ❯❯❯ clang -v
     Apple LLVM version 7.0.2 (clang-700.1.81)
     Target: x86_64-apple-darwin15.2.0
     Thread model: posix

And mac os x version
 
    ❯❯❯ uname -a
    Darwin darbymac.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

**Comment by dpayne** [comment]
Also the osx_audio branch is a dead branch, it was an attempt to try and get it working with CoreAudio, but it proved not possible in a way that was easy to use.

**Comment by dpayne** [comment]
@ClaytonSmith any update here? Did the master branch work for you?

**Comment by ClaytonSmith** [comment]
Sorry for the delay. Here are the versions of Clang and OS X I am running.

```
clang -v 
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
>>> uname -a 
Darwin Claytons-MacBook-Pro.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

Even after I installed Command Line Tools, it did not build. 

PS, I was only testing the `osx_audio` branch to see if it would build. Switched back to master and still no luck :(

**Comment by dpayne** [comment]
It looks like the latest version of clang on mac os x broke the build. I've pushed an update that should fix it, hopefully it doesn't break on older builds. Could you pull and build again?

**Comment by dpayne** [comment]
Closing this for now, since it appears to be working for me now. Let me know if it still doesn't work for you.
