### ISSUE TITLE
Build fails with Pulse-Audio on Ubuntu 16.04

### ISSUE THREAD

**Issue by educatedCaveman** [dpayne/cli-visualizer#15]
so, I've been trying to build  with Pulse audio support.  Now, I haven't compiled C in a while, so I'm not entirely certain how I need to use `make ENABLE_PULSE=1`.  my first thought was to add it to the makefile (as in replace `make` with `make ENABLE_PULSE=1`), but it fails like so:

    drake@NeonBlack:~/github/cli-visualizer-master$ sudo ./install.sh 
    mkdir -p /home/drake/github/cli-visualizer-master/build
    rm -f /home/drake/github/cli-visualizer-master/build/vis
    g++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -D_LINUX -D_ENABLE_PULSE -DNCURSESW  -fno-omit-frame-pointer -D_ENABLE_PULSE -DNCURSESW -I/usr/local/include -I/home/drake/github/cli-visualizer-master/include -I/home/drake/github/cli-visualizer-master/src -c src/vis.cpp -o /home/drake/github/cli-visualizer-master/build/vis.o
    src/vis.cpp: In function ‘int main(int, char**)’:
    src/vis.cpp:96:32: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
         system("setterm -blank 10");
                                    ^
    src/vis.cpp:97:20: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
         system("clear");
                        ^
    g++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -D_LINUX -D_ENABLE_PULSE -DNCURSESW  -fno-omit-frame-pointer -D_ENABLE_PULSE -DNCURSESW -I/usr/local/include -I/home/drake/github/cli-visualizer-master/include -I/home/drake/github/cli-visualizer-master/src -c src/Visualizer.cpp -o /home/drake/github/cli-visualizer-master/build/Visualizer.o
    In file included from src/Visualizer.cpp:10:0:
    src/Source/PulseAudioSource.h:14:30: fatal error: pulse/pulseaudio.h: No such file or directory
    compilation terminated.
    Makefile:214: recipe for target '/home/drake/github/cli-visualizer-master/build/Visualizer.o' failed
    make: *** [/home/drake/github/cli-visualizer-master/build/Visualizer.o] Error 1
    cp /home/drake/github/cli-visualizer-master/build/vis /bin/
    cp: cannot stat '/home/drake/github/cli-visualizer-master/build/vis': No such file or directory
    Makefile:206: recipe for target 'install' failed
    make: *** [install] Error 1

I've tried on its own, and if fails like below:

    drake@NeonBlack:~/github/cli-visualizer-master$ sudo make ENABLE_PULSE=1
    mkdir -p /home/drake/github/cli-visualizer-master/build
    rm -f /home/drake/github/cli-visualizer-master/build/vis
    g++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -D_LINUX -D_ENABLE_PULSE -DNCURSESW  -I/usr/local/include -I/home/drake/github/cli-visualizer-master/include -I/home/drake/github/cli-visualizer-master/src -L/usr/local/lib -o /home/drake/github/cli-visualizer-master/build/vis /home/drake/github/cli-visualizer-master/build/vis.o /home/drake/github/cli-visualizer-master/build/Visualizer.o /home/drake/github/cli-visualizer-master/build/NcursesWriter.o /home/drake/github/cli-visualizer-master/build/VisException.o /home/drake/github/cli-visualizer-master/build/ColorDefinition.o /home/drake/github/cli-visualizer-master/build/Settings.o /home/drake/github/cli-visualizer-master/build/SpectrumCircleTransformer.o /home/drake/github/cli-visualizer-master/build/LorenzTransformer.o /home/drake/github/cli-visualizer-master/build/EllipseTransformer.o /home/drake/github/cli-visualizer-master/build/SpectrumTransformer.o /home/drake/github/cli-visualizer-master/build/GenericTransformer.o /home/drake/github/cli-visualizer-master/build/NcursesUtils.o /home/drake/github/cli-visualizer-master/build/Utils.o /home/drake/github/cli-visualizer-master/build/ConfigurationUtils.o /home/drake/github/cli-visualizer-master/build/Logger.o /home/drake/github/cli-visualizer-master/build/MpdAudioSource.o /home/drake/github/cli-visualizer-master/build/PulseAudioSource.o /home/drake/github/cli-visualizer-master/build/AudioSource.o /home/drake/github/cli-visualizer-master/build/MacOsXAudioSource.o -lfftw3 -lm -lstdc++ -lpulse -lpulse-simple -lncursesw
    /usr/bin/ld: cannot find -lpulse
    /usr/bin/ld: cannot find -lpulse-simple
    collect2: error: ld returned 1 exit status
    Makefile:217: recipe for target 'vis' failed
    make: *** [vis] Error 1

is there something I'm doing wrong here?  it builds fine when i don't try with Pulse audio support.

**Comment by dpayne** [comment]
Do you have `libpulse-dev` installed?

**Comment by educatedCaveman** [comment]
that would be the issue.  you even have is listed for ubuntu.  I'm a dummy sometimes.

**Comment by dpayne** [comment]
I actually just update the ubuntu requirements section to include `libpulse-dev` this morning. I should've included it as part of the docs from the start, thanks for bringing it to my attention!

**Comment by Gfast2** [comment]
This is also works on:
```
pi@pi_3:/tmp/cli-visualizer $ uname -a
Linux pi_3 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
pi@pi_3:/tmp/cli-visualizer $ cat /etc/debian_version
9.3
```
