### ISSUE TITLE
./uninstall.sh don't working

### ISSUE THREAD

**Issue by vasiaplaton** [dpayne/cli-visualizer#152]
# ./uninstall.sh don't working
### I installed this program for fun, and now i want to uninstall it. But i can't to do it:

> ./uninstall.sh 
Makefile:5: Building with Makefile has been deprecated!
Makefile:6: Please use the cmake build process instead.
Using ltinfo
Found libpulse-simple, enabling pulseaudio support

### I tried to use cmake, but still getting error

>sudo cmake ../ && sudo make uninstall 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vasia/projects/magiclamp2/cli-visualizer/src
make: *** No rule to make target 'uninstall'.  Stop.

**Comment by vasiaplaton** [comment]
I still can remove executable from path than i know by this command:
`
which vis
/usr/local/bin/vis
`
But i think that if script for uninstalling exist, it should work.
My system is 
`
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
`

**Comment by dpayne** [comment]
You have a good point that if the uninstall script is there it should work. For now I'm choosing the sledgehammer option of removing the uninstall script. If I have time I'll come back and try to see if I can reliably make cmake uninstall vis.

**Comment by vasiaplaton** [comment]
Removing uninstalling script that a good option for now. Thank you for reply.
