### ISSUE TITLE
Changing config file does not change vis

### ISSUE THREAD

**Issue by tilktilk5** [dpayne/cli-visualizer#155]
New to linux **and** yay so I apologize if I'm missing something. 

I could not originally find the config file but after using the command `yay -Ql cli-visualizer` I was able to locate it in /usr/share/doc/cli-visualizer/config. However, none of my edits affect the visualizer as I've tried changing the bar width and the spacing as described.

Just as an experiment I copied the config file to the directory stated in the instructions but to no avail.

**Comment by dpayne** [comment]
I think the config file should be under ~/.config/vis/config. The file `/usr/share/doc/cli-visualizer/config` is just an example config.

**Comment by tilktilk5** [comment]
I copied the example config to `~/.config/vis/config` but my edits do not show up after refreshing vis.

**Comment by dpayne** [comment]
could you paste the output of `echo "kdg home ($XDG_CONFIG_HOME) home($HOME)"`

**Comment by tilktilk5** [comment]
`xdg home () home(/home/USR)` 

I read here [https://unix.stackexchange.com/questions/176896/unable-to-create-a-configuration-directory-for-fishshell-please-set-the-xdg-c](url) that it isn't necessary to set a home dir for xdg so I'm unsure if the problem actually lies with xdg or not.
