### ISSUE TITLE
regarding homebrew/dupes being closed.

### ISSUE THREAD

**Issue by darthcoder** [dpayne/cli-visualizer#156]
The Mac OSX installation instructions in the README.md suggest `brew tap homebrew/dupes` however, dupes has been deprecated officially. People not very proficient on the command line like me can get stuck trying to install it. 

Ncurses is now available simply by the usual `brew install ncurses` and hence that can be merged with the rest of the prerequisites.

**Comment by noriah** [comment]
Hi!

Added a fix to give wide support with homebrew ncurses. See #163 

Install ncurses with `brew install ncurses` 

As long as it installs to the default location, all you need to do is add `-DFORCE_NCURSESW=1` to your `cmake` command.

```shell
$ mkdir build
$ cd build
$ cmake -DFORCE_NCURSESW=1 ..
$ make
```
