### ISSUE TITLE
Dont know what i am doing wrong !pls help!

### ISSUE THREAD

**Issue by lopy67** [dpayne/cli-visualizer#18]
I am using mac os x I have done everything and whenever i run `vis` in terminal nothing happens is there a way of checking what is going wrong

**Comment by dpayne** [comment]
Are you using mpd?

**Comment by lopy67** [comment]
i did the brew mpd if that is what you are asking

**Comment by dpayne** [comment]
Well that is part of it. But you also need to configure mpd to output to a file the visualizer can use

My `mpd.conf` looks something like this

    music_directory         "~/Music/mpd"
    playlist_directory      "~/.mpd/playlists"
    db_file                 "~/.mpd/mpd.db"
    log_file                "~/.mpd/mpd.log"
    pid_file                "~/.mpd/mpd.pid"
    state_file              "~/.mpd/mpdstate"
    auto_update             "yes"
    auto_update_depth       "2"
    follow_outside_symlinks "yes"
    follow_inside_symlinks  "yes"

    audio_output {
      type                  "osx"
      name                  "CoreAudio"
      mixer_type            "software"
    }

    audio_output {
      type                  "fifo"
      name                  "my_fifo"
      path                  "/tmp/mpd.fifo"
      format                "44100:16:2"
    }

    decoder {
      plugin                "mp4ff"
      enabled               "no"
    }

    bind_to_address         "127.0.0.1"
    port                    "6600"

    user                    "dpayne"

**Comment by lopy67** [comment]
I made a mpd.conf file can it be anywhere also how do I hook it up together

**Comment by dpayne** [comment]
This guide takes you through the steps well https://timothy.sh/article/install-mpd-ncmpcpp-on-osx-yosemite. After following the guide mpd should be setup, however you also need to add the `fifo` audio_output to the config to get the visualizer working

    audio_output {
     type                  "fifo"
     name                  "my_fifo"
     path                  "/tmp/mpd.fifo"
     format                "44100:16:2"
    }

**Comment by lopy67** [comment]
this is my mpd.conf

music_directory         "~/Music"
playlist_directory              "~/.mpd/playlists"
db_file                 "~/.mpd/database"
pid_file                        "~/.mpd/pid"
state_file              "~/.mpd/state"
sticker_file                    "~/.mpd/sticker.sql"
port                            "6600"
auto_update     "yes"
audio_output {
        type            "osx"
        name            "My Mac Device"
        mixer_type      "software"
}
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

**Comment by lopy67** [comment]
**status update** i have done the mpd and ncmpcpp and when i do the mpd command nothing happens but when i do the ncmpcpp it comes up with a fancy little layout which is good i think

**Comment by dpayne** [comment]
mpd runs as a background process (aka a daemon), so mpd doing nothing is actually a good thing. Put some music under the directory `~/Music` then in nmpcpp update the library by press `u`. The mpd library will update, if you don't have many songs this should be pretty immediate. After this you can add songs to the playlist, this is a pretty useful guide of ncmpcpp's controls https://wiki.archlinux.org/index.php/ncmpcpp#Basic_usage

**Comment by lopy67** [comment]
So if that is all working what do you say the problem is with I'm thinking
Alsa or pulse audio

**Comment by dpayne** [comment]
So alsa and pulse audio do not work on mac os x. You have to play your music through mpd to to get it to work. Mac osx does uses CoreAudio instead of alsa/pulse audio, and there is not a way to make the `vis` work with CoreAudio.

**Comment by lopy67** [comment]
so basically i cant do it? on mac os x

**Comment by dpayne** [comment]
Correct, unless used with mpd mac os x will not work.

**Comment by lopy67** [comment]
Is it easy to use it with MPd

**Comment by dpayne** [comment]
If you're not used using the terminal then mpd is not the easiest music player to use. There are some mpd clients like https://github.com/TheStalwart/Theremin that are a little easier to use, you might want to try that. As long as your mpd configuration file has the `fifo` audio_output `vis` should work with any client you choose. 

I am closing this ticket, since there are not specific issues related to the visualizer here.
