### ISSUE TITLE
Colors arent correct.

### ISSUE THREAD

**Issue by Teckmek** [dpayne/cli-visualizer#187]
When i run vis the bar is a very dark purple and all thee other colors are very dark too, when i try to set a color scheme it ignores it, i have tried adding both TERM=rxvt-256color and xterm-256color to my zsh config, any help would be nice. I am on arch limux using alacritty

**Comment by Teckmek** [comment]
fixed by editing config

**Comment by aniketfuryrocks** [comment]
> fixed by editing config

What exactly did you change ?
