### ISSUE TITLE
"vis" gives error message

### ISSUE THREAD

**Issue by GGDeezNuts** [dpayne/cli-visualizer#193]
Whenever I run vis I get this message:

/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = vis::ColorDefinition; _Alloc = std::allocator<vis::ColorDefinition>; std::vector<_Tp, _Alloc>::reference = vis::ColorDefinition&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
         fish: Job 1, 'vis' terminated by signal SIGABRT (Abort)

I have no idea what any of it means

OS is Arch Linux

**Comment by bdefore** [comment]
i get the same on manjaro

**Comment by GGDeezNuts** [comment]
Solved it by downloading the git package and running the install script.
