### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by spencerhakim** [dpayne/cli-visualizer#20]
While working on proper OS X support, I discovered that the `vis` name has apparently been claimed in BSD-land for over two decades. It hasn't caused me any trouble, but I'm honestly not sure how important the real `vis` is. Locally I've just changed my makefile to use `TARGET=viz` instead, and that doesn't seem to conflict with anything else as far as I can tell. Just thought I'd throw this out there.

**Comment by dpayne** [comment]
Yeah, I'm somewhat split on what to do. I didn't realize there was a conflict until after I had made the project public. I don't really like changing the name, but I don't really see an alternative.

**Comment by Syrup-tan** [comment]
My ``/usr/bin`` came before ``/usr/local/bin`` in my ``$PATH``, so I was bit by this. ``vis(1)`` just waits for input on stdin, so I hadn't realized that it wasn't even running the cli-visualizer.

Might be good to note this in the ``README.md`` for OS X users (just have them check ``which vis`` or something)

**Comment by dpayne** [comment]
That is a great idea. Added a trouble shooting section with your suggestion.
