### ISSUE TITLE
I got blank screen on Ubuntu

### ISSUE THREAD

**Issue by xahmad7** [dpayne/cli-visualizer#208]
Hello
I've followed the instructions and installed cli-visualizer
But when i run it in terminal using Ubuntu 23.04 i got blank screen
Please help

**Comment by Hex-4** [comment]
Have you set up an audio source (pulse, alsa, etc.)?

**Comment by xahmad7** [comment]
Yes

**Comment by rogonow** [comment]
Try my color scheme:
[https://github.com/dpayne/cli-visualizer/issues/168#issuecomment-1281471557](https://github.com/dpayne/cli-visualizer/issues/168#issuecomment-1281471557)

**Comment by xahmad7** [comment]
Thank You
After re-installing it worked
