### ISSUE TITLE
Bars not moving

### ISSUE THREAD

**Issue by Sempiternal-Futility** [dpayne/cli-visualizer#212]
So i installed it on debian 11, but the bars are just standing still, even when audio is playing?

My config files are the default ones, nothing has been tempered with.

How do i fix that?

**Comment by rogonow** [comment]
Make shore the configuration file has the right audio source. Mine is coded as:
```
##Sets the audio sources to use.
##Currently available ones are "mpd", "pulse", "shmem", and "alsa". Defaults to "pulse".
#activated by
audio.sources=pulse
```
location: [/home/youraccountnamehere/.config/vis/config](/home/youraccountnamehere/.config/vis/)

**Comment by Sempiternal-Futility** [comment]
@rogonow it works now! thanks! What worked for me was just setting it to default. (adding a '#' at the beggining)
