### ISSUE TITLE
ALSA configuration breaks sound system

### ISSUE THREAD

**Issue by jonpatterns** [dpayne/cli-visualizer#23]
Using ALSA and adding the following code to /etc/asound.conf breaks the sound system:

```
pcm.!default {
    type file               # File PCM
    slave.pcm "hw:0,0"      # This should match the playback device at /proc/asound/devices
    file "|safe_fifo /tmp/audio" #safe_fifo will be in the cli-visualizer/bin/safe_fifo directory
    format raw              # File format ("raw" or "wav")
    perm 0666               # Output file permission (octal, def. 0600)
}

```

sound no longer plays and audio program deadbeef crashes when attempting to play an mp3.

speaker-test -t sine -f 2600 results in:

`Playback open error: -16,Device or resource busy`

System information:

cat /proc/asound/modules

```
 0 snd_ca0106
 1 snd_intel8x0
```

I'm using the Creative Labs ca0106 card

uname -a
`Linux dimension 4.1.23-1-MANJARO #1 SMP PREEMPT Sun Apr 24 10:46:46 UTC 2016 i686 GNU/Linux`

**Comment by dpayne** [comment]
Did you install the program `safe_fifo`, it's under the `bin` when building from source?

I will say that ALSA support is very experimental, however pulseaudio support works pretty well out of the box.

**Comment by jonpatterns** [comment]
I installed via AUR. What is the best way to build and install safe_fifo ?

**Comment by dpayne** [comment]
You have to build from source. I did not auto package it in AUR because it is pretty experimental and I do not want to install a program on a user's system when I am not sure it will not break something. After building from source it will be in the `bin/safe_fifo`.

**Comment by jonpatterns** [comment]
Great, thanks for the reply. I'll give building from source a go.

**Comment by dpayne** [comment]
@jonpatterns I am closing this for now. Please re-open if it is still broken for you.
