### ISSUE TITLE
Nothing happens on OS X

### ISSUE THREAD

**Issue by WatermelonDriveway** [dpayne/cli-visualizer#24]
```
brew install fftw
Warning: fftw-3.3.4_1 already installed
brew tap homebrew/dupes
brew install ncurses
Warning: homebrew/dupes/ncurses-6.0_1 already installed

```

Seemed to install fine after cloning the repo and entering "./install.sh" and the config file is in the right place.  I have mpd+ncmpcpp working fine, and my mpd.conf contains the fifo output lines.

Any idea?

**Comment by dpayne** [comment]
Could you paste the output of `which vis`?

**Comment by WatermelonDriveway** [comment]
`/usr/bin/vis`

**Comment by dpayne** [comment]
Can you try running it from the build folder directly. `./build/vis`

**Comment by WatermelonDriveway** [comment]
When I run it with just 'vis', it looks like it's hanging waiting for something (still displaying my original prompt), but when I run it directly from the build folder, it does remove my prompt from the terminal as if trying to display something.  I can post screenshots if that isn't descriptive enough

**Comment by dpayne** [comment]
I believe you're running into this issue https://github.com/dpayne/cli-visualizer#vis-hangs-with-no-output , basically it's a naming conflict with another program. The new issue (remove the prompt but still nothing), is most likely a config issue. For `mpd` the vis config should have the lines

    audio.sources=mpd
    mpd.fifo.path=/tmp/mpd.fifo

**Comment by WatermelonDriveway** [comment]
Issue solved.. awesome.  audio.sources was set to pulse, and both of those two lines you just sent were both commented off by default in the config, which I didn't notice.  

Thanks!
