### ISSUE TITLE
AUR PKGBUILD fails

### ISSUE THREAD

**Issue by Fredo699** [dpayne/cli-visualizer#25]
I'm trying to install this project from the AUR. I didn't touch the PKGBUILD or the .install file, and it spat out a compiler error.

>g++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -D_LINUX -D_ENABLE_PULSE -Wl,-O1,--sort-common,--as-needed,-z,relro -fno-omit-frame-pointer -D_ENABLE_PULSE -I/usr/local/include -I/tmp/yaourt-tmp-fredo/aur-cli-visualizer/src/cli-visualizer-1.1/include -I/tmp/yaourt-tmp-fredo/aur-cli-visualizer/src/cli-visualizer-1.1/src -c src/Transformer/SpectrumCircleTransformer.cpp -o /tmp/yaourt-tmp-fredo/aur-cli-visualizer/src/cli-visualizer-1.1/build/SpectrumCircleTransformer.o
src/Transformer/SpectrumCircleTransformer.cpp: In member function ‘virtual void vis::SpectrumCircleTransformer::draw_bars(const std::vector<double>&, const std::vector<double>&, int32_t, bool, const wstring&, vis::NcursesWriter*)’:
src/Transformer/SpectrumCircleTransformer.cpp:38:9: error: ‘sqrt’ is not a member of ‘std’
         std::sqrt(std::pow(half_height, 2) + std::pow(half_height, 2));
         ^~~
src/Transformer/SpectrumCircleTransformer.cpp:38:19: error: ‘pow’ is not a member of ‘std’
         std::sqrt(std::pow(half_height, 2) + std::pow(half_height, 2));
                   ^~~
src/Transformer/SpectrumCircleTransformer.cpp:38:46: error: ‘pow’ is not a member of ‘std’
         std::sqrt(std::pow(half_height, 2) + std::pow(half_height, 2));
                                              ^~~
src/Transformer/SpectrumCircleTransformer.cpp:48:43: error: ‘cos’ is not a member of ‘std’
             auto x = static_cast<int32_t>(std::cos(rad) * row_index);
                                           ^~~
src/Transformer/SpectrumCircleTransformer.cpp:50:43: error: ‘sin’ is not a member of ‘std’
             auto y = static_cast<int32_t>(std::sin(rad) * row_index);
                                           ^~~
src/Transformer/SpectrumCircleTransformer.cpp:52:35: error: ‘sqrt’ is not a member of ‘std’
             const auto distance = std::sqrt(std::pow(x, 2) + std::pow(y, 2));
                                   ^~~
src/Transformer/SpectrumCircleTransformer.cpp:52:45: error: ‘pow’ is not a member of ‘std’
             const auto distance = std::sqrt(std::pow(x, 2) + std::pow(y, 2));
                                             ^~~
src/Transformer/SpectrumCircleTransformer.cpp:52:62: error: ‘pow’ is not a member of ‘std’
             const auto distance = std::sqrt(std::pow(x, 2) + std::pow(y, 2));
                                                              ^~~
Makefile:214: recipe for target '/tmp/yaourt-tmp-fredo/aur-cli-visualizer/src/cli-visualizer-1.1/build/SpectrumCircleTransformer.o' failed
make: *** [/tmp/yaourt-tmp-fredo/aur-cli-visualizer/src/cli-visualizer-1.1/build/SpectrumCircleTransformer.o] Error 1

Sorry if this is difficult to parse through, I'm not sure how to make it pretty.

**Comment by dpayne** [comment]
Could you paste the output of ```g++ --version```?

**Comment by Fredo699** [comment]
g++ (GCC) 6.1.1 20160501
Copyright (C) 2016 Free Software Foundation, Inc.

**Comment by DuckThom** [comment]
I've had a look at the PGKBUILD and I think it might be because it's pulling an older version (Release 1.1).
The version the PGKBUILD uses doesn't include commit https://github.com/dpayne/cli-visualizer/commit/768544880e8f0ddad5d57b8da5a7c60ec8657f8d `Fixing build on gcc 6+`

**Comment by dpayne** [comment]
I bumped the AUR build to the latest. This should be fixed now. Thanks for finding this, originally I was only checking the git AUR build instead of the release version.
