### ISSUE TITLE
Lorenz is showing ??? characters on OSX

### ISSUE THREAD

**Issue by raviu** [dpayne/cli-visualizer#29]
I think this has something to do with ncurses, I'm not sure. It looks like this screenshot: http://i.imgur.com/CJ5QWYj.jpg

Any idea why I'm seeing this?

**Comment by dpayne** [comment]
Unfortunately OSX doesn't support wide characters correctly. Can you add the following to your config.

    visualizer.lorenz.character=#

**Comment by raviu** [comment]
I'm going with " ". Thanks, this is much better than what it was! 👍
