### ISSUE TITLE
Some bars get stuck at a certain level

### ISSUE THREAD

**Issue by AConsolePeasant** [dpayne/cli-visualizer#3]
I love the program, just got a strange problem where, after a while of playing, the music the bars can get 'stuck' at a point, and not go below that point, but they can go above that point, after going above the stuck level, it returns back to the stuck point.

The same thing happens with ellipse mode too, can't really tell with lorenz

It sometimes goes away after changing to a song, possibly with a blank part at the start of the song.

Photo of it when no audio is being played. https://i.imgur.com/Q0O7q2V.png

Video of music playing, and the bug happening
https://youtu.be/rteCqFnHmPA

Tested on the latest commit.

Config: https://gist.github.com/AConsolePeasant/5fdb31de56e0662b3ed5

**Comment by dpayne** [comment]
I've been trying to track down this bug for a while now but it has proven to be elusive. I had thought it a bug in the part of the code that generates the falloff effect. I had also thought I had fixed it : (

Were you building from source, if so can you build with "make clean && make". Sometimes building with make doesn't pick up all the changes if you are building in the same directory. Also were you using pulse or mpd as the audio source?

**Comment by dpayne** [comment]
Actually could you pull from master and re-build with "make clean && make". I have potentially fixed the issue.

**Comment by AConsolePeasant** [comment]
Looks like it's fixed.
