### ISSUE TITLE
16 color terminal

### ISSUE THREAD

**Issue by petervaro** [dpayne/cli-visualizer#31]
Is it possible to add support for non 256 color terminals? For example `$TERM=screen-16color`. 

*(Out of curiosity: Why is 256 color required in the first place?)*

**Comment by DuckThom** [comment]
`TERM=screen-16color` seems to be working fine for me, or am I missing something?

![](http://lunamoonfang.nl/s/IKZAm/full)

**Comment by petervaro** [comment]
Interesting.. for me, it only gives the "black" color for every possible `color.scheme`. In this image I use the `rainbow` theme:

![screenshot_2016-12-10_00-22-56](https://cloud.githubusercontent.com/assets/2691101/21069154/246fef2a-be6f-11e6-812d-2d884dcdb362.png)

It is `urxvt` with `tmux`, and I tried it without `tmux` as well, same result. (All the other applications are working fine and have colors, eg. `cmus`, `vim`, etc.)

**Comment by dpayne** [comment]
Rainbow theme will always use 256 bit color. However you can specify your own theme in the config https://github.com/dpayne/cli-visualizer#colors. So for example for 16 bit color you could put a file called `basic_colors` at `~/.config/vis/colors/basic_colors` with the contents

```4
12
6
14
2
10
11
3
5
1
13
9
7
15
0```

Then set the theme to `basic_colors`.

**Comment by petervaro** [comment]
@dpayne I already tried `blue`, `basic_colors` and defining my own theme. Each attempt has the exact same effect. I know for a fact that my config file has been read, since I can change `visualizer.spectrum.bar.spacing` and `visualizer.spectrum.bar.width` for instance, and their changes do take effect. I've tried defining my own colors with both ANSI names and numbers.

**Comment by DuckThom** [comment]
Strange, I'm using `urxvt` as well.
The colors @dpayne put in his comment are the same colors I'm using as well.
It's the same color scheme that's in the examples folder of this repo.

**Comment by petervaro** [comment]
Update: the most strange part is, that if I try it in `xfce terminal` or `terminator` both with`tmux` I have the same colorless result, however, if I exit from `tmux`, it works perfectly fine. It wouldn't be that strange, if the same thing would happen with `urxvt`, but with that emulator, it doesn't matter wether I'm in `tmux` or not.

When I'm in `xfce terminal` inside `tmux` the `$TERM=screen-16color` (not working), when I exit `tmux` and `$TERM=xterm-256color` (working). Exactly the same environment variable values go for `terminator`. For `urxvt` with or without `tmux` I have the `$TERM=screen-16color` (I defined these values in `.Xresources` as `URxvt*termName: screen-16color` and in `.tmux.conf` as `set-option -g default-terminal 'screen-16color'`.

**Comment by dpayne** [comment]
This should be working now on the latest build. If it doesn't let me know and I'll look at it again.

**Comment by petervaro** [comment]
*It is working on my machine*&#8482;

Cheers :)

**Comment by petervaro** [comment]
I was too quick on closing this issue -- yes, now I have working colors. but I can't change them! It doesn't matter what color scheme I put into the config it does not take any effect! (Other changes in the config file has immediate effect.)

**Comment by dpayne** [comment]
Could you try with both `$TERM=screen-16color` and `$TERM=xterm-256color`. Could you also post your full config and color scheme.

**Comment by petervaro** [comment]
Okay, I think you will hate me because of this, but I figured out what went wrong, and at the same time I have a suggestion on this one on UI point of view. So basically this sentence in the README misguided me:

> The color scheme must be defined at `~/.config/vis/colors/color_scheme` directory.

Which could be understood as: the colors-scheme file should be put into the `~/.config/vis/colors/color_scheme` directory, that is in case of a file `mycs` would be: `~/.config/vis/colors/color_scheme/mycs`. I figured out this only now, when I double checked everything to post you my files, and when I reread the last code block in the README file:

> `# The color scheme must be in ~/.config/vis/colors/ directory.`

So my suggestions are:

1. in the README you should use some sort of a "user-defined" value notation, like: `~/.config/vis/colors/<name_of_the_color_scheme>`

2. no errors should pass silently in the program: it may seem like a good idea, that `vis` is capable of deciding wether it should use a default value or not based on the validity of inputs, but let me tell you, this will lead to confusion on the user's side. IMO it would be better to terminate the program if the config contains:

    1. unspecified key

    2. invalud value for a key

And it should report back to the user before it terminates. If this would've happened, I would've never opened this issue in the first place, because I would've figured out that my colors-scheme is at the wrong directory, when `vis` would've return the prompt to me after printing the following error message:

```
Ivalid value for `colors.scheme' in file: `/home/petervaro/.config/vis/config' at line 1:
    Color scheme cannot be found: `my_test_scheme'
```

Anyway, everything is working now, and I have to tell you, you guys did a great job so far, `vis` is amazing! Keep up the good work!

**Comment by dpayne** [comment]
Thanks for the suggestions! I've updated the README with your suggestion, later when I'll have time I'll add the error checking.
