### ISSUE TITLE
visualizer not working

### ISSUE THREAD

**Issue by LordNDHuy** [dpayne/cli-visualizer#32]
I am using Arch.
I installed vis both form aur and from github.
the only one that works is the spectrum. the other 2 doesnot work, it is just a blank screen.
how do i fix it?

**Comment by dpayne** [comment]
Could you try setting the lorenz and ellipse characters to something else. For example, adding the following to the config at `~/.config/vis/config`

    visualizer.lorenz.character=#
    visualizer.ellipse.character=#

**Comment by hplewis** [comment]
I was having this same issue where it only worked for spectrum, but not lorenz or ellipse. Your solution worked for me @dpayne. I also decided to see if setting to to a space would work and it does. I'm guessing the default might just not be getting set somewhere for Arch?

```
visualizer.lorenz.character= 
visualizer.ellipse.character= 
```

**Comment by dpayne** [comment]
Did you build from source recently? What you described _should_ have been fixed with this commit https://github.com/dpayne/cli-visualizer/commit/05d56c5f2021502f2f3589eb21ddb78a0d05eac5, but it's possible there's still a bug here.

**Comment by hplewis** [comment]
I used the [version from the AUR](https://aur.archlinux.org/packages/cli-visualizer/) which looks like it was last updated right before that commit. So that explains why it is broken for me. Thanks!

**Comment by dpayne** [comment]
Ah ok, I'll update the version on AUR.

**Comment by rosshadden** [comment]
Neither the version on AUR nor `cli-visualizer-git` work for me---the latter of which is just installing from source---nor does installing from source manually.

**Comment by greenbigfrog** [comment]
Just installed `cli-visualizer-git` from the AUR, and lorenz and ellipse won't display without setting the character in the config

**Comment by greenbigfrog** [comment]
Specifying ` `(space) as character works though
