### ISSUE TITLE
PulseAudio pulls from sources instead of sinks

### ISSUE THREAD

**Issue by drayneman** [dpayne/cli-visualizer#33]
Hello,
First, I apologize if it turns out this doesn't have to do with your program. However, as far as I can tell, vis is listening to my input sources rather than my output sinks.
For example, when I run `pacmd list-sinks | grep -e 'name:' -e 'index'`, it spits this out:

     index: 0
        name: <alsa_output.pci-0000_01_00.1.hdmi-stereo>
     index: 1
        name: <alsa_output.pci-0000_00_1b.0.analog-stereo>`

So I type in 1 for the `audio.pulse.source=` field. The spectrum, however responds to all audio input, so when i checked the sources output (`pacmd list-sources | grep -e device.string -e 'name:'`), it came up with this:

      name: <alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor>
                device.string = "1"
      name: <alsa_input.usb-OmniVision_Technologies__Inc.-S2640-07.05.28.1_Monitor_Integrated_Webcam-02.analog-stereo>
                device.string = "front:2"
      name: <alsa_output.pci-0000_00_1b.0.analog-stereo.monitor>
                device.string = "0"
      name: <alsa_input.pci-0000_00_1b.0.analog-stereo>
                device.string = "front:0"

Here, 1 is also my default source for PulseAudio. What's more is that `audio.pulse.source=` displays a valid spectrum for all inputs up to 3, which is my number of PulseAudio sources.

Is there a way for me to modify this to pull from my PulseAudio sinks? Thank you for any input.

**Comment by dpayne** [comment]
This is pretty weird. I did have this issue once with the pure alsa method, but I haven't seen it happen for pulse audio. The code to pick the sink is here https://github.com/dpayne/cli-visualizer/blob/master/src/Source/PulseAudioSource.cpp#L53. What it _should_ do is just use pulseaudios default sink, but it looks like that's not what's happening here.

Could you post the full `pacmd list-sinks` output?

**Comment by drayneman** [comment]
Thank you for the response.
This is my output for `pacmd list-sinks`:

2 sink(s) available.
    index: 0
        name: <alsa_output.pci-0000_01_00.1.hdmi-stereo>
        driver: <module-alsa-card.c>
        flags: HARDWARE DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 9050
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        base volume: 65536 / 100% / 0.00 dB
        volume steps: 65537
        muted: no
        current latency: 0.00 ms
        max request: 0 KiB
        max rewind: 0 KiB
        monitor source: 0
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        used by: 0
        linked by: 0
        configured latency: 0.00 ms; range is 0.50 .. 1999.82 ms
        card: 0 <alsa_card.pci-0000_01_00.1>
        module: 6
        properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "HDMI 0"
                alsa.id = "HDMI 0"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "3"
                alsa.card = "1"
                alsa.card_name = "HDA NVidia"
                alsa.long_card_name = "HDA NVidia at 0xf3080000 irq 17"
                alsa.driver_name = "snd_hda_intel"
                device.bus_path = "pci-0000:01:00.1"
                sysfs.path = "/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1"
                device.bus = "pci"
                device.vendor.id = "10de"
                device.vendor.name = "NVIDIA Corporation"
                device.product.id = "0e1b"
                device.product.name = "GK107 HDMI Audio Controller"
                device.string = "hdmi:1"
                device.buffering.buffer_size = "352768"
                device.buffering.fragment_size = "176384"
                device.access_mode = "mmap+timer"
                device.profile.name = "hdmi-stereo"
                device.profile.description = "Digital Stereo (HDMI)"
                device.description = "GK107 HDMI Audio Controller Digital Stereo (HDMI)"
                alsa.mixer_name = "Nvidia GPU 42 HDMI/DP"
                alsa.components = "HDA:10de0042,38422652,00100100"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-pci"
        ports:
                hdmi-output-0: HDMI / DisplayPort (priority 5900, latency offset 0 usec, available: no)
                        properties:
                                device.icon_name = "video-display"
        active port: <hdmi-output-0>
  * index: 1
        name: <alsa_output.pci-0000_00_1b.0.analog-stereo>
        driver: <module-alsa-card.c>
        flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 9959
        volume: front-left: 28312 /  43% / -21.87 dB,   front-right: 28312 /  43% / -21.87 dB
                balance 0.00
        base volume: 65536 / 100% / 0.00 dB
        volume steps: 65537
        muted: no
        current latency: 0.00 ms
        max request: 0 KiB
        max rewind: 0 KiB
        monitor source: 1
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        used by: 0
        linked by: 0
        configured latency: 0.00 ms; range is 0.50 .. 2000.00 ms
        card: 1 <alsa_card.pci-0000_00_1b.0>
        module: 7
        properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "ALC1150 Analog"
                alsa.id = "ALC1150 Analog"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "0"
                alsa.card_name = "HDA Intel PCH"
                alsa.long_card_name = "HDA Intel PCH at 0xf3230000 irq 30"
                alsa.driver_name = "snd_hda_intel"
                device.bus_path = "pci-0000:00:1b.0"
                sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card0"
                device.bus = "pci"
                device.vendor.id = "8086"
                device.vendor.name = "Intel Corporation"
                device.product.id = "8c20"
                device.product.name = "8 Series/C220 Series Chipset High Definition Audio Controller"
                device.form_factor = "internal"
                device.string = "front:0"
                device.buffering.buffer_size = "352800"
                device.buffering.fragment_size = "176400"
                device.access_mode = "mmap+timer"
                device.profile.name = "analog-stereo"
                device.profile.description = "Analog Stereo"
                device.description = "Built-in Audio Analog Stereo"
                alsa.mixer_name = "Realtek ALC1150"
                alsa.components = "HDA:10ec0900,18491151,00100001"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-pci"
        ports:
                analog-output-lineout: Line Out (priority 9900, latency offset 0 usec, available: yes)
                        properties:

                analog-output-headphones: Headphones (priority 9000, latency offset 0 usec, available: no)
                        properties:
                                device.icon_name = "audio-headphones"
        active port: <analog-output-lineout>

I'm not affiliated with C++ at all, so I probably won't be able to contribute anything. Again,  thanks for your time.

**Comment by dpayne** [comment]
You might have already tried this but could you try running with the default config, so the config would look like. 

    #audio.pulse.source=0

**Comment by drayneman** [comment]
Hi, sorry for the long wait.
After messing with some PulseAudio controls, I went into pavucontrol and switched my Built-in Audio from Analog Stereo Duplex to Analog Surround 5.1 Output, which apparently affects what sink vis listens to. Sorry for your trouble, as it turns out that this had nothing to do with your program.

**Comment by dpayne** [comment]
no worries, I'm glad you got it fixed! I'm closing the issue now but please let me know if you find any other issues.
