### ISSUE TITLE
Visualizer fails to work if started at 30fps in mono mode.

### ISSUE THREAD

**Issue by skewerr** [dpayne/cli-visualizer#36]
For some reason, setting the fps to 30(only value I tested) and setting mono mode to false:

```
visualizer.fps = 30
audio.stereo.enabled = false
```

makes the visualizer fail to work on startup.

I can use it at 30fps if I start it at another value(or at 30fps in stereo mode), change the configuration file, then reload with `r`, however.

**Comment by dpayne** [comment]
I can't seem to reproduce this issue. Would you mind posting your full config, as well as what setup you are using (i.e. linux, osx)?

**Comment by skewerr** [comment]
Sure, here:

```
visualizer.fps=30

audio.sources=mpd

# Defaults to "/tmp/mpd.fifo"
mpd.fifo.path=/tmp/mpd.fifo

audio.stereo.enabled=false

# Defaults to spectrum,ellipse,lorenz
visualizers=spectrum,ellipse,lorenz

visualizer.spectrum.character=█
visualizer.spectrum.bar.width=1
visualizer.spectrum.bar.spacing=1

# Available smoothing options are monstercat, sgs, none.
visualizer.spectrum.smoothing.mode=monstercat

visualizer.ellipse.character=#
visualizer.lorenz.character=#

colors.scheme=default
```

I'm using Arch Linux, installed cli-visualizer through the `cli-visualizer` package on the AUR. Terminal's rxvt-unicode, if it helps in any way.

**Comment by dpayne** [comment]
Monstercat does work for me at 30 fps, but it's possible it's broken on your screen demensions. I am still debugging it to figure it out. In the mean time could you try a different smoothing mode. Depending on the song `sgs` usually looks a lot smoother than `monstercat`. 

    visualizer.spectrum.smoothing.mode=sgs

**Comment by skewerr** [comment]
I've been using it at 25fps without an issue, it just seemed like the right thing to do to report the bug.

That said, at 30fps, `sgs` also doesn't work when the program starts. As for screen dimensions: you mean the terminal's? I ran it on windows of different sizes and the result was the same. ☹️

**Comment by dpayne** [comment]
I've gone tried a lot of different things to reproduce this and still haven't been able to figure it out. Does it still happen on the latest build?

**Comment by skewerr** [comment]
Whoa, seems to have been fixed in the latest build...?

Sorry I neglected this issue for a long while. I was doing just fine with 25fps. Just reinstalled `cli-visualizer` from the AUR to get the latest sources and it seems to work just fine with 30 set as the framerate.
