### ISSUE TITLE
Some bars will not move

### ISSUE THREAD

**Issue by ABCeedee** [dpayne/cli-visualizer#37]
Everything seems to be working, except the right-most bar (associated with the highest frequency) does not appear to move at all.

I am using mpd + ncmpcpp. Below is a link to my vis config file.

http://pastebin.com/raw/P3Sq3HVk

**Comment by dpayne** [comment]
My guess is this is related to the margins, and that I am rounding somewhere inconsistently. Whenever I get some free time I'll look into it.

**Comment by dpayne** [comment]
This should now be fixed.
