### ISSUE TITLE
Keybinding to toggle stereo on/off

### ISSUE THREAD

**Issue by thejmazz** [dpayne/cli-visualizer#40]
First off, thanks for this awesome software!

I have the following feature request to add a keybinding to toggle between stereo enabled and disabled. Perhaps `s`.

With limited vertical space, stereo not enabled looks nicer than enabled. 

*limited space, stereo enabled*
<img width="1680" alt="screen shot 2017-01-22 at 2 09 26 pm" src="https://cloud.githubusercontent.com/assets/1270998/22185093/01331036-e0ad-11e6-9b06-967b197fe548.png">

*limited space, stereo disabled*
<img width="1680" alt="screen shot 2017-01-22 at 2 09 03 pm" src="https://cloud.githubusercontent.com/assets/1270998/22185094/01374b38-e0ad-11e6-8d6e-bc90c5e453e9.png">

*ample space, stereo enabled*
<img width="1680" alt="screen shot 2017-01-22 at 2 09 33 pm" src="https://cloud.githubusercontent.com/assets/1270998/22185092/0126ac42-e0ad-11e6-97b6-0dbc8407a25b.png">

I'd like to be able to quickly switch between these as I may be using the visualization either as a split pane in tmux alongside ncmpcpp or standalone in its own window. My current solution is to edit the config and reload in only one of my running vis instances.

**Comment by dpayne** [comment]
Great idea! Added just now in the master branch.
