### ISSUE TITLE
Tearing/Corruption occurs with non standard tab sizes on xterm

### ISSUE THREAD

**Issue by jgkamat** [dpayne/cli-visualizer#42]
This is probably a bug in xterm or ncurses, but I thought I would report it here, to see if anyone else can reproduce it (and let you know).

When setting the tabs sizes in your terminal to a non stanard size (eg: 4), corruption occurs.

This problem is most pronounced in xterm, but it seems to affect other terminals too. When on non standard tab sizes in urxvt, there is corruption, but it is much less (I'm getting this sort of corruption when the screen is very large in urxvt, but that's probably unrelated).

`$ tabs -8` (this is good!)

![2017-03-04-011335_1909x1056_scrot](https://cloud.githubusercontent.com/assets/4349709/23576587/ccc810f4-0077-11e7-86ec-2af0fb6f2915.png)

`$ tabs -4`

![2017-03-04-011400_1901x1051_scrot](https://cloud.githubusercontent.com/assets/4349709/23576588/e027732e-0077-11e7-86a9-b19f4cff0124.png)

`$ tabs -0`

![2017-03-04-011430_1910x1054_scrot](https://cloud.githubusercontent.com/assets/4349709/23576596/f167ad8e-0077-11e7-8bd5-0e2aa3250570.png)

```
xterm: XTerm(325)
ncurses: 6
```

Let me know if you cannot reproduce or if you want additional information!

**Comment by dpayne** [comment]
Sorry for the late response here. I am unable to reproduce the issue. I tried with both urxvt and regular xterm. Is it possible this is a really old or really low power machine? My hunch is that the the computer isn't powerful enough to clear the screen before the next redraw. It is pretty odd though that tabs size would make a performance difference.

**Comment by jgkamat** [comment]
I don't think my machine is low powered, it can handle cli-vsualizer at 60fps normally. This bug happens for me even when I set the fps as low as 10, so I don't think it's performance related (and I see this even when the terminal is very small). I'm not sure what could be causing it, maybe it's a weird issue with my specific version of ncurses, let me know if you have any other ideas.. :cry:

**Comment by dpayne** [comment]
Which version of ncurses are you using, you should be able to get it with `cat /usr/include/ncurses.h| grep VERSION` or with your package manager.

**Comment by jgkamat** [comment]
Here is the output of the command:
```
#define NCURSES_VERSION_MAJOR 6
#define NCURSES_VERSION_MINOR 0
#define NCURSES_VERSION_PATCH 20150808
#undef  NCURSES_VERSION
#define NCURSES_VERSION "6.0"
#define NCURSES_MOUSE_VERSION 2
#  define NCURSES_EVENT_VERSION	1
#define curses_version() NCURSES_VERSION
#if NCURSES_MOUSE_VERSION > 1
#if NCURSES_MOUSE_VERSION > 1
```

According to my package manager I'm using ncurses 6.0-r1

**Comment by dpayne** [comment]
This is very odd, I cannot reproduce it at all. My only suggestion would be to uninstall ncurses then try re-installing from the latest source from here http://invisible-mirror.net/archives/ncurses/current/. Your ncurses version isn't that old so I'd be a little surprised if that fixed it but it might be worth a shot.

**Comment by jgkamat** [comment]
I'm not running remotely, it's all on the local machine. I'll try out the ncurses thing in a couple of weeks, I don't want to mess around too much with my system right now. I'll try it out and let you know what I find! :smile:

**Comment by jgkamat** [comment]
@dpayne I upgraded my ncurses version and that seems to have fixed all my problems. Since I can't reproduce anymore, closing.
