### ISSUE TITLE
(OS X) Visualizing Stereo Output (from all applications)

### ISSUE THREAD

**Issue by jemhuntr** [dpayne/cli-visualizer#43]
Related: https://github.com/dpayne/cli-visualizer/issues/41

Is it possible to visualize sound output (e.g. Spotify, Youtube running on Chrome, games, etc) on OS X? Currently stuck with the blank screen because I literally have no music on my laptop (mpd only plays local music and I stream all music).

Thanks :)

**Comment by dpayne** [comment]
Unfortunately there's no good way to do this. OS X's sound system is fairly sandboxed, only the kernel and the program outputting the sound can read the sound output. I was experimenting in a branch with a custom loopback service similar to https://rogueamoeba.com/loopback/ but I couldn't figure out a way to do it that didn't require the user execute a lot of different steps.
