### ISSUE TITLE
Spectrum inverted?

### ISSUE THREAD

**Issue by Scoopta** [dpayne/cli-visualizer#46]
I recently upgraded my hardware which involved recompiling my kernel. After I got my system up and running again vis was no longer working so I recompiled it from source and now it does weird things. The other two visuallizers work but I only ever used spectrum. Spectrum for some reason is like inverted. I say like because I'm not sure what to call it. When I launch vis it basically just clears my terminal. If I then drag my mouse to highlight the visualizer that's when I can see it but the second I stop highlighting it disappears. I've played around with the config but haven't been able to figure it out and the log doesn't say anything.

**Comment by dpayne** [comment]
That is pretty odd. Do you mind attaching a screenshot and your config?

**Comment by dpayne** [comment]
It is hard to tell, but my initial guess is that it is not getting the sound source at all. Meaning that it thinks the source is muted or cannot find the correct pulse audio sink. Would you mind posting the output of `pacmd list-sinks  | grep -e 'name:'  -e 'index'`.

**Comment by Scoopta** [comment]
The reason I took a video was to show that. It does get the audio. For me whenever I start vis it has all the bars at 100% as it did in the start. Then I played some audio which is what caused it to go down into the line at the end. Here is the output you requested though:
`index: 0
	name: <alsa_output.pci-0000_09_00.1.hdmi-stereo>
  * index: 1
	name: <alsa_output.usb-Logitech_Logitech_G933_Gaming_Wireless_Headset-00.analog-stereo>
    index: 2
	name: <alsa_output.pci-0000_12_00.3.analog-stereo>`

**Comment by dpayne** [comment]
Could you try changing pulse audio sources, try 0 and 2. For example,

```audio.pulse.source=0```

**Comment by Scoopta** [comment]
It does the same thing the only difference is when I highlight it the bars stay at 100% even if I play audio.

**Comment by dpayne** [comment]
@Scoopta do you mind running this again with the latest build? I've made a lot of bug fixes especially to the way ncurses handles colors.

**Comment by Scoopta** [comment]
Sure no problem.

**Comment by Scoopta** [comment]
Hmmmmm...well that didn't go well
`/mnt/Storage/Downloads/cli-visualizer/build/NcursesWriter.o: In function 'vis::NcursesWriter::setup_extended_color_pairs()':
NcursesWriter.cpp:(.text+0x318): undefined reference to 'init_extended_pair'
NcursesWriter.cpp:(.text+0x329): undefined reference to 'init_extended_pair'
collect2: error: ld returned 1 exit status
Makefile:234: recipe for target 'vis' failed
make: *** [vis] Error 1`

**Comment by dpayne** [comment]
The build error should now be fixed.

**Comment by Scoopta** [comment]
=D it works now.
