### ISSUE TITLE
Compilation error in Alpine

### ISSUE THREAD

**Issue by LiamMartens** [dpayne/cli-visualizer#48]
Getting the following errors
(the `ncurses-dev` package for Alpine is installed)

```
src/Writer/NcursesWriter.cpp: In member function 'void vis::NcursesWriter::write_background(int32_t, int32_t, vis::ColorIndex, const wstring&)':
src/Writer/NcursesWriter.cpp:62:41: error: 'mvaddwstr' was not declared in this scope
     mvaddwstr(height, width, msg.c_str());
                                         ^
src/Writer/NcursesWriter.cpp: In member function 'void vis::NcursesWriter::write_foreground(int32_t, int32_t, vis::ColorIndex, const wstring&)':
src/Writer/NcursesWriter.cpp:73:41: error: 'mvaddwstr' was not declared in this scope
     mvaddwstr(height, width, msg.c_str());
                                         ^
make: *** [Makefile:233: /cli-visualizer/build/NcursesWriter.o] Error 1
```

**Comment by dpayne** [comment]
This is most likely due to the ncurses not being compiled with wide character support. Do you know if alpine has a separate wide character version of ncurses?

**Comment by LiamMartens** [comment]
There is a package called `ncurses5-widec-libs` but installing that package does not fix it as I'm guessing it isn't a dev package and there's no other dev packages available either.

**Comment by dtzWill** [comment]
I had similar problem when using musl, poking at ncurses headers shows this:

```
#ifndef NCURSES_WIDECHAR
#if defined(_XOPEN_SOURCE_EXTENDED) || (defined(_XOPEN_SOURCE) && (_XOPEN_SOURCE - 0 >= 500))
#define NCURSES_WIDECHAR 1
#else
#define NCURSES_WIDECHAR 0
#endif
#endif /* NCURSES_WIDECHAR */
```

So I added `-D_XOPEN_SOURCE=500` to my CFLAGS and that seems to have done the trick.
Setting `_XOPEN_SOURCE_EXTENDED` or `NCURSES_WIDECHAR` directly would probably work as well.

Hope this helps!
