### ISSUE TITLE
Q: Can I get the raw spectrum totals out via fifo

### ISSUE THREAD

**Issue by technosf** [dpayne/cli-visualizer#51]
A question:

In the same way cli can pull the PCM from MPD fifo, can cli dump analyzed band amplitudes out to a fifo (along with displaying it)?

I'd like to pick up the spectrum and send it to another device to display in an alternate manner.

Cheers!

T

**Comment by dpayne** [comment]
I am not sure what your use case is, is there a good reason to use cli-visualizers output instead of getting it directly from mpd fifo file?

**Comment by technosf** [comment]
Hi Darby,

I am trying to avoid recreating the whole MPD->FFT->value array pipe-line. I'd prefer to use something that already works. I have a bit of a time crunch.

T

**Comment by dpayne** [comment]
I still do not really see the use case. If all you need is the FFT transform, there are plenty of tools to do that fairly easily. I used libfftw http://www.fftw.org/fftw3_doc/Using-Plans.html. If you feel strongly about the feature, please feel free to create a pull request for it.
