### ISSUE TITLE
DESTDIR is not respected

### ISSUE THREAD

**Issue by blshkv** [dpayne/cli-visualizer#52]
I'm building the tool in a sandbox env is getting the following message:
```
>>> Install cli-visualizer-1.6 into /var/tmp/portage/media-sound/cli-visualizer-1.6/image/ category media-sound
make -j4 DESTDIR=/var/tmp/portage/media-sound/cli-visualizer-1.6/image/ install 
which: no ccache in (/usr/lib/portage/python2.7/ebuild-helpers/xattr:/usr/lib/portage/python2.7/ebuild-helpers:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0:/usr/x86_64-pc-linux-gnu/aarch64-unknown-linux-gnu/gcc-bin/6.3.0)
Found libpulse-simple, enabling pulseaudio support
cp /var/tmp/portage/media-sound/cli-visualizer-1.6/work/cli-visualizer-1.6/build/vis /bin/
 * ACCESS DENIED:  open_wr:      /bin/vis
cp: cannot create regular file '/bin/vis': Permission denied
make: *** [Makefile:225: install] Error 1
 * ERROR: media-sound/cli-visualizer-1.6::local-overlay failed (install phase):
```

Please fix installation by adding a DESTDIR variable: 
```
install: 
  cp $(BUILD_DIR)/$(TARGET) $(DESTDIR)/$(PREFIX)
```

For more details, see the following doc:
https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by blshkv** [comment]
You might also need to make sure that the directory exist because the next error I'm facing is the following:
```
cp /var/tmp/portage/media-sound/cli-visualizer-1.6/work/cli-visualizer-1.6/build/vis /var/tmp/portage/media-sound/cli-visualizer-1.6/image//bin/
cp: cannot create regular file '/var/tmp/portage/media-sound/cli-visualizer-1.6/image//bin/': Not a direct
```

**Comment by blshkv** [comment]
Did you fix the bug or just ignored my request?

**Comment by dpayne** [comment]
Sorry I'm not always responsive as I should be on github. To give you more detail, I don't really consider this to be a bug. A user can already specify PREFIX to whatever directory they want so I don't see the need for an additional variable. Additionally I'm not sure I like auto creating install directories. When the directory is `~/bin` it might make sense but if it's something like `/usr/bin/` that might be bad since the script could be creating the directory with wrong permissions.

**Comment by blshkv** [comment]
Please read the link which I gave. You are confusing these two variables. In short, PREFIX is set to ```/usr``` in many distros (and /usr/local/ by default).

DESTDIR has a totally different meaning. It allows to install the entire tool in that directory, choot into it and run from. Its value is not set (empty) by default, however it is useful for many distro like Gentoo where they install tool in a sandbox environment first.

As for the ```bin``` folder, it goes along with DISTDIR. Gentoo compiles all tools in /var/tmp and fails to install all bins by default.

P.S. Disclaimer: I'm a Pentoo developer and wrote an ebuild. That should help other Gentoo users like this guys https://github.com/dpayne/cli-visualizer/issues/83.

**Comment by dpayne** [comment]
I am pretty unfamiliar with the gentoo build process and with GNU standards. When I originally created the install script, it was mostly meant for people building it themselves. I had assumed, incorrectly, that distros would build with distro specific scripts (e.g. deb package, or PKGBUILD). You appear to be very knowledgable on the subject, especially with Gentoo. If you want to improve the project, please feel free to make a PR.
