### ISSUE TITLE
Lower Visualizer Tolerance

### ISSUE THREAD

**Issue by Camotubi** [dpayne/cli-visualizer#54]
Hi, i would like the visualizer to respond more to the audio. I dont know how to explain it, or what terms to use but ( atleast with lorenze and ellipse, spectrum its ok) my audio output has to be very loud to see something "meaningfull" in the visualizer. 
This is what it looks like at a acceptable volume
![2017-08-03-190637_631x570_scrot](https://user-images.githubusercontent.com/4031324/28948943-e4456270-787e-11e7-97cc-9855b34e3379.png)
In order to see this
![2017-08-03-190833_545x620_scrot](https://user-images.githubusercontent.com/4031324/28949004-566f57a2-787f-11e7-9d96-a6990cddf84c.png)
![2017-08-03-190927_695x726_scrot](https://user-images.githubusercontent.com/4031324/28949005-56708e56-787f-11e7-92f6-fd77f0602ab4.png)
The volume has to be at ear-bleeding levels ( very load) 
I have read the readme and the examples but I havent found anything to "lower the tolerance".
I'm on fedora 25 and pulse audio.
Anyway thanks for sharing this awesome software.

**Comment by dpayne** [comment]
This is a good idea. For the regular spectrum bars I auto-scale to fit the screen, however for the other visualizers I didn't add that. I'll look at seeing if I can figure out auto-scaling for the other visualizers. If I can't figure it out, I'll just add a manual scaler. I found manual scaling pretty annoying since volume can change from song-to-song quite a lot.

**Comment by Camotubi** [comment]
Thanks dude. Despite all the hassle of resolving the dependencies to build it, Im really enjoying your work. Looking forward to the scalling feature.

**Comment by dpayne** [comment]
I added a scaling multiplier settings as well as keys to increase/decrease it. https://github.com/dpayne/cli-visualizer#scaling Please let me know if it doesn't work or you think it can be improved in some way. Thanks again for the recommendation for this.
