### ISSUE TITLE
Instruction for Fedora 25/26

### ISSUE THREAD

**Issue by Camotubi** [dpayne/cli-visualizer#57]
Hi again, I think that the documentation can be improved. Unfortunately the names of the dependencies on fedora has a completely different name. Last week I spent like an hours looking for the dependencies. If you could add these to the readme it would be awesome
sudo dnf install fftw-devel fftw-doc <---- (I'm not sure if the docs are needed)
sudo dnf install ncurses-devel
sudo dnf install pulseaudio-libs-devel.
I have only tested this on fedora 25 and 26.
PD. The scaling multiplier is working great.

**Comment by dpayne** [comment]
Done! https://github.com/dpayne/cli-visualizer#fedora
