### ISSUE TITLE
q or CTRL-C does not kill vis

### ISSUE THREAD

**Issue by matthiasbeyer** [dpayne/cli-visualizer#6]
For me, neither `q` nor `ctrl-c` kill vis.

I'm on bc0104eb57e7a0b3821510bc8f93cf5d1154fa8e

using xterm plain or xterm with tmux.

**Comment by dpayne** [comment]
Is this with pulse audio or mpd?

**Comment by matthiasbeyer** [comment]
with neither. Just plain `vis` called.

**Comment by dpayne** [comment]
What audio source? It should be defined in the config under `audio.sources=mpd`. If you do not have a config, then the default is pulseaudio.

**Comment by matthiasbeyer** [comment]
Also: Nothing. I just installed it and tried to run it. No config file, no nothing. I had to kill it (with `kill -9` because otherwise it won't die).

**Comment by dpayne** [comment]
Could you try running it with the audio source set to mpd

Create a file at `~/.config/vis/config`
Then add `audio.sources=mpd`

**Comment by dpayne** [comment]
I've moved the CTRL-C signal handling code around. Could you pull the latest version and try that?

**Comment by dpayne** [comment]
I'm closing this for now. Please update this thread if you still have issues.
