### ISSUE TITLE
Unable to set visualizer.spectrum.bar.spacing=0 after recent commits

### ISSUE THREAD

**Issue by dasnoopy** [dpayne/cli-visualizer#60]
Compiling  from git with recent commits (403),  **cli-visualizer**   show this error at lauch

`Invalid settings visualizer.spectrum.bar.spacing=0`

and it doesn't run;  with e.g. value = 1  it works fine.

previous version (at least commit 376) works fine also setting 0 as value

Regards

**Comment by dpayne** [comment]
Fixed, thanks for reporting this!
