### ISSUE TITLE
vis clears the screen when exiting

### ISSUE THREAD

**Issue by anowlcalledjosh** [dpayne/cli-visualizer#61]
Demonstration: <https://asciinema.org/a/oC6jCraGE32OBSfzb1rgG7EOa>

tl;dw: ncmpcpp (and less, and mutt, and vim) don't clear the whole screen when they exit – they remove their content from the terminal, but nothing more, as if they exited with no output. vis clears the entire screen (like pressing ^L), which is disconcerting when you're expecting your previous commands to still be visible. It would be nice if vis behaved like other applications and didn't remove output that it didn't create.

**Comment by dpayne** [comment]
So this was done intentionally so that no artifacts are visualizers are left on the screen after exit. I _think_ I fixed most of the issues that were causing the artifacts so I'll disable clearing for now.
