### ISSUE TITLE
color scheme ignored

### ISSUE THREAD

**Issue by nonchip** [dpayne/cli-visualizer#64]
excerpt from `config`:

    colors.override.terminal=true
    colors.scheme=blackblue

whole `colors/blackblue`:

    gradient=true
    #000000
    #0000ff

result:
![https://imgur.com/a/z0psg](https://i.imgur.com/XzfllWm.png)

i also tried `black` and `blue` instead of the hex codes, same result.

`$TERM` set by tmux is `screen-256color` ; outer `$TERM` is `st-256color` (using the suckless terminal)

the color scheme file is being loaded, since when I rename it or change the config setting to something inexistant, vis would throw an error.

**Comment by dpayne** [comment]
Could you try setting term to something else, for example

```export TERM=rxvt-256color```

**Comment by nonchip** [comment]
that strangely kinda works, but why? 0.o

am I missing some termcap file?

also "kinda" means: it blends from a light cyan to black to blue, instead of black to blue.

**Comment by nonchip** [comment]
what I don't understand is why `rxvt-` works but `screen-` doesn't. both have the same color count according to `tput colors`

**Comment by nonchip** [comment]
fun fact:

    #include <ncurses.h>
    #include <stdio.h>
    void main(void){
      initscr();
      printf("%d\n",COLORS);
    }

prints `0` no matter what environment I'm using.

**Comment by nonchip** [comment]
found the problem. my terminfo for `screen-256color` includes `max_colors#256` but for `rxvt-256color` it's:
```
$ TERM=rxvt-256color infocmp -L | grep color
#       Reconstructed via infocmp from file: /usr/share/terminfo/r/rxvt-256color
rxvt-256color|rxvt 2.7.9 with xterm 256-colors,
        auto_right_margin, back_color_erase,
        columns#80, init_tabs#8, lines#24, max_colors#256,
        initialize_color=\E]4;%p1%d;rgb\072%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\,
```

so I was just missing some more termcaps.

**Comment by nonchip** [comment]
just another observation: after fixing it, `reset` doesn't work any more for fixing the colors. neither does `stty -g` to backup the config (leaves the messed up colors but kills key handling for `[Home]` `[End]` etc)...

**Comment by nonchip** [comment]
also "works" still means I get the wrong colors (cyan to black to blue instead of black to blue) but at least I don't get random ones anymore.

**Comment by nonchip** [comment]
the best I could achieve:
![](https://i.imgur.com/pAhkt8Y.png)

without `colors.override` and with TERM=screen-256color-bce-s.

**Comment by nonchip** [comment]
fun fact: using [true color](https://gist.github.com/XVilka/8346728) works perfectly, but that's sadly not supported by ncurses (yet?)

**Comment by nonchip** [comment]
I SOLVED IT, kinda:

    wget https://git.suckless.org/st/plain/st.info
    tic st.info

and using `TERM=st-256color` INSIDE tmux too (because it's compatible anyway).

still doesn't correctly manage black->blue though (uses cyan->black->blue instead) but other colors work as expected.

**Comment by nonchip** [comment]
OH, now i actually solved it: `gradient=true` was actually misinterpreted as cyan. seems you only check for `false`, not explicit `true` when stripping that from the table of colors to load :P

**Comment by nonchip** [comment]
fun fact: now it even works with the override on and DOES NOT mess up my shell :D

**Comment by dpayne** [comment]
Thanks for all the info! I'll fix the true check, besides that I don't think there is much I can change since it is dependent on ncurses. Eventually true color could be supported by dropping ncurses altogether, but that would require a lot of work since it require a lot of different handling of different terminal settings.
