### ISSUE TITLE
Lower frequencies

### ISSUE THREAD

**Issue by Akhetopnu** [dpayne/cli-visualizer#68]
This is more of a question/request. The visualizer is very cool but it looks like the lower frequencies are not being shows on the spectrum. I mean I can see that this program registers them and shows a higher 'hill' but it's usually only 1-2 columns. I don't know how much work would it be to kinda shift the whole spectrum some 30-40hz to the right, so that the lowest ones would be  more visible. I'm just guessing 30-40 because I',m not sure what is the current lowest frequency bar.

Cheers

**Comment by theonaciri** [comment]
As described in the doc you can configure the audio range with this:
`#Configures the samples rate and the cutoff frequencies.
audio.sampling.frequency=44100
audio.low.cutoff.frequency=22050
audio.high.cutoff.frequency=30`
The configuration file is installed under "~/.config/vis/config".
