### ISSUE TITLE
blank screen in tmux pane

### ISSUE THREAD

**Issue by cirrusUK** [dpayne/cli-visualizer#69]
is it expected behaviour to get blank screen when run from within a tmux session ? or maybe i am missing something, thanks for the code.

**Comment by dpayne** [comment]
It's not expected. Does it work outside of tmux? If so then it's likely something to do with TERM.

**Comment by cirrusUK** [comment]
@dpayne  yes it works fine outwith tmux, i use TERM=xterm-256color
 variable. I get same same result in termite and the other vte3's, and in st, xterm, thanks for the pointer i will play around with TERM variable.

**Comment by dpayne** [comment]
Can you try `export TERM=rxvt-256color`?

**Comment by cirrusUK** [comment]
@dpayne  SPlendid sir, thats me sorted !
Regards
