### ISSUE TITLE
Running install.sh throw error

### ISSUE THREAD

**Issue by Lukaboot** [dpayne/cli-visualizer#73]
src/Source/PulseAudioSource.h:15:25: fatal error: pulse/error.h: No such file or directory

Distribution is Solus and the dependencies are satisfied as far as I can tell

**Comment by dpayne** [comment]
Is the pulse audio development library installed?

**Comment by weilbith** [comment]
How is this library called. A fix search does not give the answer.

**Comment by weilbith** [comment]
Got it 'libpulse-dev'.

**Comment by dpayne** [comment]
Does it work with libpulse-dev installed?

**Comment by weilbith** [comment]
Yes, for it does.
