### ISSUE TITLE
problem installing on Fedora 27

### ISSUE THREAD

**Issue by Stephr1** [dpayne/cli-visualizer#77]
After building pre-requisites, ./install.sh command creates following error code:

[root@localhost cli-visualizer-master]# ./install.sh              
which: no clang in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin)
which: no ccache in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin)
Found libpulse-simple, enabling pulseaudio support
which: no clang in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin)
which: no ccache in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin)
Found libpulse-simple, enabling pulseaudio support
mkdir -p /home/user/Desktop/cli-visualizer-master/build
rm -f /home/user/Desktop/cli-visualizer-master/build/vis
g++ -std=c++14 -O3 -march=native -ffast-math -fno-omit-frame-pointer -D__extern_always_inline=inline -D_XOPEN_SOURCE_EXTENDED -D_LINUX -D_ENABLE_PULSE -DNCURSESW  -fno-omit-frame-pointer -D_ENABLE_PULSE -DNCURSESW -I/usr/local/include -I/home/user/Desktop/cli-visualizer-master/include -I/home/user/Desktop/cli-visualizer-master/src -c src/vis.cpp -o /home/user/Desktop/cli-visualizer-master/build/vis.o
omit-frame-pointer -D_ENABLE_PULSE -DNCURSESW -I/usr/local/include -I/home/user/Desktop/cli-visualizer-master/include -I/home/user/Desktop/cli-visualizer-master/src -c src/vis.cpp -o /home/user/Desktop/cli-visualizer-master/build/vis.o

The last 4 lines repeat for a bit more than a page with different file paths and ends with:

gcc bin/safe_fifo.c -o bin/safe_fifo
which: no clang in (/sbin:/bin:/usr/sbin:/usr/bin)
which: no ccache in (/sbin:/bin:/usr/sbin:/usr/bin)
Found libpulse-simple, enabling pulseaudio support
cp /home/user/Desktop/cli-visualizer-master/build/vis /bin/

Is there a missing library perhaps?

Thank you

**Comment by dpayne** [comment]
The clang and ccache checks are just there for checking different build methods, they are not need to build. Did the build finish? If not were there any other errors?

**Comment by Stephr1** [comment]
My bad it did install, I had a lot of errors before that took a while to figure out which made me paranoid.
Thanks
