### ISSUE TITLE
Spectrum glitch - gap in the middle

### ISSUE THREAD

**Issue by wjagodfrey** [dpayne/cli-visualizer#78]
Any ideas what might be causing this?

Perhaps a change of ncurses version?

<img width="434" alt="screen shot 2018-01-16 at 1 06 09 pm" src="https://user-images.githubusercontent.com/5732688/34966122-4d8fe360-fabe-11e7-8fea-1f065e28557f.png">

**Comment by dpayne** [comment]
Can you try setting `export TERM=rxvt-256color`?

**Comment by wjagodfrey** [comment]
That did it! Apologies, I'd set this on another computer (same terminal)
and hadn't seen a difference. Thanks for the hint.

Wilfred

On Jan 17, 2018 06:56, "Darby Payne" <notifications@github.com> wrote:

Can you try setting export TERM=rxvt-256color?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dpayne/cli-visualizer/issues/78#issuecomment-358048951>,
or mute the thread
