### ISSUE TITLE
Weird colors with rainbow

### ISSUE THREAD

**Issue by spike11302000** [dpayne/cli-visualizer#80]
![vis](https://user-images.githubusercontent.com/12355526/35255080-ddc17e78-ffb2-11e7-9a95-5190cf06e18d.PNG)
i get wierd colors with "rainbow" color
even with "export TERM=rxvt-256color" it is still weird

**Comment by dpayne** [comment]
What terminal are you running?

**Comment by spike11302000** [comment]
putty but im also using the ubuntu server console

**Comment by dpayne** [comment]
Is putty setup to run 256 colors? It looks like it can only detect the basic colors so it won't use the rainbow scheme,

**Comment by spike11302000** [comment]
i also get the same issue when im displaying it on the video output with ubuntu server

**Comment by dpayne** [comment]
Can you try following the steps here https://superuser.com/questions/436910/emulate-256-colors-in-putty-terminal?

**Comment by dpayne** [comment]
I'm closing this for now. I am pretty it just has to do with correctly setting up 256 colors in putty.
