### ISSUE TITLE
[macOS] vis hangs, nothing in the log files

### ISSUE THREAD

**Issue by Thibaulltt** [dpayne/cli-visualizer#82]
N.B : I've already made an alias as not to run `/usr/bin/vis` instead of `/usr/local/bin/vis`

When launching vis, nothing happens. It just stays there, not being able to launch the visualizer window. I thought it was because I was in a tmux session, so I closed tmux and tried it without anything else running.

`mpd` is working fine, `ncmpcpp-visualizer` is also working, and yet `vis` hangs at startup. Running under iTerm2, macOS 10.13.3, and installation did not report any errors.

NOTE : it should be noted that when my fifo file was not named correctly, `vis` did launch, but no visualizer bar was to be seen (which is expected, since it could not find the desired fifo file

**Comment by Thibaulltt** [comment]
Nevermind, needed a complete system restart in order for the fifo to get recognised apparently.

`vis` now works inside of a `tmux` session.

@dpayne Could you add a section to the MacOS troubleshooting, citing maybe a system restart might be needed ?

**Comment by Thibaulltt** [comment]
Oh, and feel free to close the issue whenever.

**Comment by dpayne** [comment]
hrm, a full restart shouldn't be required. There's a couple of issues it could have been, possibly mpd needed to be restarted to start writing to fifo? Either way I am closing for now since it will be hard to tell retroactively what happened.
