### ISSUE TITLE
Unable to install on Gentoo

### ISSUE THREAD

**Issue by c0rva** [dpayne/cli-visualizer#83]
g++ seems to be building just fine (for pulseaudio), until at the end, where I get:

collect2: error: ld returned 1 exit status
make: *** [Makefile:249: vis] Error 1
which: no ccache in (/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/5/bin)
Found libpulse-simple, enabling pulseaudio support
cp /home/maya/Downloads/cli-visualizer-master/build/vis /bin/
cp: cannot stat '/home/maya/Downloads/cli-visualizer-master/build/vis': No such file or directory
make: *** [Makefile:238: install] Error 1

I'm assuming the ccache error isnt a problem, but for the copying, I can't figure it out. The path is correct. I have the correct pulseaudio dependencies installed, although this may be the problem, considering I'm not entirely sure of the equivalents for Gentoo.

**Comment by dpayne** [comment]
can you post the full output of `make clean && make`

**Comment by c0rva** [comment]
which: no clang in (/sbin:/bin:/usr/sbin:/usr/bin)
which: no ccache in (/sbin:/bin:/usr/sbin:/usr/bin)
Found libpulse-simple, enabling pulseaudio support
which: no clang in (/sbin:/bin:/usr/sbin:/usr/bin)
which: no ccache in (/sbin:/bin:/usr/sbin:/usr/bin)
Found libpulse-simple, enabling pulseaudio support
make: Nothing to be done for 'install.sh'

**Comment by SHGuy1** [comment]
You have to install the clang package and the ccache package.

First, add clang to your use flags in `/etc/portage/make.conf`
`USE="clang ..."`
and update `@world `
`#emerge -a --changed-use --deep @world`
than install clang and ccache
`# emerge -a sys-devel/clang dev-util/ccache `

now rerun the install-script in cli-visualizer and if this error continues you have to link clang manuelly with
`# ln -s /usr/lib/llvm/5/bin/clang /usr/bin/`

**Comment by dpayne** [comment]
I dropped the requirement for ccache and clang, so hopefully it should work on gentoo now without issues.

**Comment by dpayne** [comment]
This should be fixed with the new cmake build process.
