### ISSUE TITLE
Install doesn't warn if run as non-root

### ISSUE THREAD

**Issue by dt-rush** [dpayne/cli-visualizer#88]
In order to run `ldconfig` and detect pulse, the install needs to have access to /sbin (hence, root permissions), but the `README` suggests that we install via `./install.sh`. From the `Makefile`:

```
ifndef ENABLE_PULSE
CHECK_PULSE=$(shell ldconfig -p | grep libpulse-simple)
```

Should the `README` be changed to suggest `sudo ./install.sh`?

**Comment by dt-rush** [comment]
I made this issue because I initially didn't notice, as the installation appeared to complete successfully.

**Comment by dpayne** [comment]
done!
