### ISSUE TITLE
Non-functional in tmux and/or st

### ISSUE THREAD

**Issue by HalosGhost** [dpayne/cli-visualizer#9]
Running ``vis`` in ``st`` or in any of several terminals under ``tmux`` results in a blank screen with nothing being painted.

There are no errors to report as far as I can tell, simply no function. Note, this was tested using the pulse backend, but since the same configuration was functional under other terminals, I assume this is immaterial.

**Comment by dpayne** [comment]
My initial guess is that tmux doesn't support 256 colors. Could you try with a different color scheme? The color scheme can be defined in the colors directory, usually under `~/.config/vis/colors/`. The config option `colors.scheme` can be used to set the color scheme.

For example, copy the file copying the colorscheme [blue](https://github.com/dpayne/cli-visualizer/blob/master/examples/blue) to `~/.config/vis/colors/blue` then set `colors.scheme=blue`.

**Comment by HalosGhost** [comment]
Both tmux and st have support for 256 color, and I have my terminfo set to ``tmux-256color`` which is the correct one for such a thing (available since ncurses 6).

In addition, I tried changing the color scheme to basic_colors and I still got the blank screen.

**Comment by dpayne** [comment]
Does it work with `st` without `tmux`?

**Comment by HalosGhost** [comment]
Yesterday, it did not work in ``st`` even when not under ``tmux``. But in a terminal where it does work, it stops working under ``tmux``. If these should be separated to two separate issues, that's fine :)

I will checkout that branch and give it a shot!

**Comment by dpayne** [comment]
Would you mind pulling the branch `always_enable_colors` another time. I've made one other change to always enable 256 colors. So far I've been unable to reproduce this with `tmux`, it is working with the latest arch linux packages.

**Comment by HalosGhost** [comment]
All right, I have an update. First, it seems I may have made a foolish mistake earlier and passed ``ENABLE_PULSE=1`` _after_ ``make`` instead of before. However, after having changed it, ``vis`` still produces no visible output in ``st``.

However, after making sure to pass it as an environment variable, the same thing happens: it works in terminals other than ``st``, but not inside ``tmux`` and it does not work in ``st`` at all.

**Comment by dpayne** [comment]
For both the `tmux` issue and the `st` one solution is to set `TERM` to `xterm-256color`,  `urxvt-256color` also seemed to work for me. This can be done at compile time when building `st` using this method https://wiki.archlinux.org/index.php/St#Term or by running `export TERM='xterm-256color'`. The compile time way seems to be the recommended way for `st`. Note that both basic and 256 colors should be supported.

Please update this thread if you still have issues or if you find a better way.

**Comment by HalosGhost** [comment]
@dpayne, so the issue then is that ``vis`` is incompatible with both terminfos tmux-256color and st-256color?

**Comment by dpayne** [comment]
So the actual issue is pretty annoying. vis uses ncurses, which uses `$TERM` to figure out what colors are supported and how to output them since different terminals have different escape codes. So for example when `tmux` is run without setting `$TERM`, `vis` still works it's just that all the colors are either black or transparent. You can see this if you set your terminal to transparent, then some sections of the bars will show up black and some clear.

The two solutions appear to be either stop using `ncurses` or have the user set the `$TERM` variable, both solutions are terrible with the second being slightly less so. Removing `ncurses` would be a huge pain since it handles a lot of the peculiarities of various terminals. I really do not like that the user has to set a shell variable or even worse change a compile time setting in the terminal, but the alternative of abandoning `ncurses` is not going to happen anytime soon.

**Comment by HalosGhost** [comment]
Well, actually, it sounds like you have an implicit dependency on xterm/urxvt's terminfo. ``$TERM`` declares the terminfo to use, but I have it set (I just have it set to ``tmux-256color`` when in ``tmux`` and ``st-256color`` when in ``st`` without ``tmux``).

**Comment by dpayne** [comment]
I do not use `$TERM` anywhere in the code, however `ncurses` does. From the docs http://linux.die.net/man/3/ncurses 

     TERM
       Denotes your terminal type. Each terminal type is distinct, though many are similar.

The current version of `ncurses` does not recognize `tmux-256color` or `st-256color` so it assumes a default that clearly does not work.

**Comment by HalosGhost** [comment]
Which version of ``ncurses`` are you referring to? The latest version of ncurses (at least on Arch) provides both ``tmux-256color`` and ``st-256color``. See below:

```console
$ pacman -Qi ncurses|grep Version
Version        : 6.0-4
$ pacman -Ql ncurses|grep -e 'st-256color' -e 'tmux-256color'
ncurses /usr/share/terminfo/s/st-256color
ncurses /usr/share/terminfo/t/tmux-256color
```

**Comment by dpayne** [comment]
You are right. I was using a custom version of `ncurses` but the latest version appears to have it, but I still see the same issue. However this just makes the issue more perplexing. `vis` does not use terminfo directly in any way, it always goes through `ncurses`.

**Comment by HalosGhost** [comment]
I will take a look at the code this weekend and see if I cannot figure out what may be going on. Thank you for your time, regardless!

**Comment by dpayne** [comment]
Could you run `tput colors` with `tmux` and in `st`?

On my system, with `tmux` I get `8` even though 256 colors should be supported. After running `export TERM='xterm-256color'`, `tput colors` shows `256` and `vis` will show all colors. Again, thanks for all the work investigating this; this is definitely an issue just one I do not see a good solution to. Please update this thread or open another issue if you find a better solution.

**Comment by HalosGhost** [comment]
``tput colors`` shows ``256`` in both ``tmux`` and ``st``.  You may have ``8`` showing up because ``tmux`` does not default to using ``tmux-256color``, but that is what I have it set to use.
