### ISSUE TITLE
Installation fails when parent directories have spaces

### ISSUE THREAD

**Issue by galenasphaug** [dpayne/cli-visualizer#91]
I tried installing cli-visualizer with `sudo ./install.sh` under the directory `/home/galenasphaug/Programming/Github\ Stuff/cli-visualizer`, and the makefile produced this:

`Found libpulse-simple, enabling pulseaudio support
Makefile:245: *** mixed implicit and normal rules: deprecated syntax
Makefile:252: warning: overriding recipe for target '/home/galenasphaug/Programming/Github'
Makefile:246: warning: ignoring old recipe for target '/home/galenasphaug/Programming/Github'
Makefile:251: *** mixed implicit and normal rules: deprecated syntax
Makefile:259: warning: overriding recipe for target '/home/galenasphaug/Programming/Github'
Makefile:252: warning: ignoring old recipe for target '/home/galenasphaug/Programming/Github'
Makefile:258: *** mixed implicit and normal rules: deprecated syntax
Found libpulse-simple, enabling pulseaudio support
Makefile:245: *** mixed implicit and normal rules: deprecated syntax
Makefile:252: warning: overriding recipe for target '/home/galenasphaug/Programming/Github'
Makefile:246: warning: ignoring old recipe for target '/home/galenasphaug/Programming/Github'
Makefile:251: *** mixed implicit and normal rules: deprecated syntax
Makefile:259: warning: overriding recipe for target '/home/galenasphaug/Programming/Github'
Makefile:252: warning: ignoring old recipe for target '/home/galenasphaug/Programming/Github'
Makefile:258: *** mixed implicit and normal rules: deprecated syntax
mkdir -p /home/galenasphaug/Programming/Github stuff/cli-visualizer/build
rm -f /home/galenasphaug/Programming/Github stuff/cli-visualizer/build/vis
rm: cannot remove '/home/galenasphaug/Programming/Github': Is a directory
Makefile:200: recipe for target 'prepare' failed
make: *** [prepare] Error 1
Found libpulse-simple, enabling pulseaudio support
Makefile:245: *** mixed implicit and normal rules: deprecated syntax
Makefile:252: warning: overriding recipe for target '/home/galenasphaug/Programming/Github'
Makefile:246: warning: ignoring old recipe for target '/home/galenasphaug/Programming/Github'
Makefile:251: *** mixed implicit and normal rules: deprecated syntax
Makefile:259: warning: overriding recipe for target '/home/galenasphaug/Programming/Github'
Makefile:252: warning: ignoring old recipe for target '/home/galenasphaug/Programming/Github'
Makefile:258: *** mixed implicit and normal rules: deprecated syntax
cp /home/galenasphaug/Programming/Github stuff/cli-visualizer/build/vis /bin/
cp: -r not specified; omitting directory '/home/galenasphaug/Programming/Github'
cp: cannot stat 'stuff/cli-visualizer/build/vis': No such file or directory
Makefile:238: recipe for target 'install' failed
make: *** [install] Error 1`

The three lines
`mkdir -p /home/galenasphaug/Programming/Github stuff/cli-visualizer/build`
`rm -f /home/galenasphaug/Programming/Github stuff/cli-visualizer/build/vis`
`rm: cannot remove '/home/galenasphaug/Programming/Github': Is a directory`
are what concern me. This creates a `Github` folder in the same directory as `Github\ stuff` and also creates `stuff/cli-visualizer/build/vis` in the working directory.

**Comment by dpayne** [comment]
I did my best to make it possible to install to a directory with spaces. The build unfortunately needs to be in a path without spaces, it is a functional limitation of make. If you have a solution for it, please let me know.
