### ISSUE TITLE
Permission problems

### ISSUE THREAD

**Issue by Spark010** [dpayne/cli-visualizer#92]
so the program installs correctly  except all the directories and files it creates has root as it's owner ... this leads to a big amount of time to reclaim ownship of the configuration files... plus the colors are not respected once you do that because it does not look at the file thinking it's not mine I won't use it....
this is a problem that touch the makefile and the install script
also you can copy the program generated in ~/bin for the user binaries ... it's better because the user can retain permission over the file created

**Comment by dpayne** [comment]
This was more of a mistake in the readme than anything else. I have updated the readme to not run the install script as sudo. The binary will still be copied to `/bin/` or whatever the PREFIX is set to. I don't really see the to change that, the user can always copy the binary from the build directory to any where they want with whatever permissions they want.
